= Background

link:../../index.html[Home] » link:../index.html[Jade Regent 2020] » link:index.html[Story Journal]

While the region known today as Varisia has long been inhabited (all the way back to the Age of Legend, when powerful wizards known as runelords ruled the region as the Empire of Thassilon), it wasn’t until relatively recently that it came to the attention of the nations of the Inner Sea. Cheliax made an aggressive attempt to colonize Varisia, but conflict with its native peoples and the remote location made such attempts difficult. By the time of Aroden’s death and the Chelish Civil War, Cheliax’s colonies in Varisia had already become independent.

While the inland highlands of Varisia remain wild and untamed, a fair amount of its coastal lowlands are now civilized. Three cities in particular—Korvosa, Magnimar, and Riddleport—represent civilization’s three greatest modern triumphs in the region. Each of these cities has a number of smaller villages in its outlying reaches, and of these smaller settlements, the town of Sandpoint is among the largest and most successful—the perfect spot for fledgling heroes to start careers of adventure.

== Standpoint

Founded in 4666 ar along the Lost Coast, just a day’s ride north of Magnimar, Sandpoint has grown into a rustic and prosperous town of just over 1,200 citizens. The town has dealt with a number of disasters in the past 5 decades, including several powerful storms, goblin uprisings, trouble with dragons, devastating fires, and deranged serial killers. Yet Sandpoint weathered these trials and emerged stronger after each one. Today, the town hosts several thriving industries (including lumber, fishing, farming, and glassblowing) as well as a number of unique businesses and entertainment venues. The town seems comfortable in its transitory position between rural charm and urban convenience, and is a healthy and vibrant settlement despite its slow growth.

*Government* autocracy (mayor) +
*Population* 1,240 (1,116 humans, 37 halflings, 25 elves, 24 dwarves, 13 gnomes, 13 half-elves, 12 half-orcs)
[horizontal]
Notable NPCs::
Mayor Kendra Deverin +
Sheriff Belor Hemlock +
Town Priest Abstalar Zantus +
Nobleman Titus Scarnetti +
Nobleman Ethram Valdemar +
Noblewoman Ameiko Kaijitsu

Although Sandpoint is a relatively small town with citizens prone to living relaxed and unexciting lives, the town’s hinterlands hold numerous opportunities for adventure. As such, many of Sandpoint’s businesses cater to adventurers. The following locations and services offered in Sandpoint should be of particular interest to adventuring PCs.

Sandpoint Cathedral:: Tended by Father Abstalar Zantus, a cleric of Desna, the Sandpoint Cathedral is a pantheistic temple that contains shrines to Abadar, Desna, Erastil, Gozreh, Sarenrae, and Shelyn. Zantus and his four 1st-level acolytes can provide a limited amount of healing every day.

Places to Relax:: Sandpoint offers several places to relax and spend the night, including taverns, inns, and even a brothel. The White Deer and the Rusty Dragon are Sandpoint’s two inns—their prices are comparable, but the Rusty Dragon specifically caters to adventurers, and its owner, Ameiko Kaijitsu, has been known to offer discount rates to adventurers in return for entertaining tales of their escapades. For taverns and eateries, visitors can choose between Cracktooth’s Tavern (specializing in amateur entertainments, ale, and crunchy snacks), Fatman’s Feedbag (specializing in enormous servings of mediocre food, rum, and bar fights), the Hagfish (specializing in seafood, gambling, and boasting), Risa’s Place (specializing in potato dishes, cider, and stories; particularly valued by the locals since this place isn’t well known by visitors), and the Rusty Dragon (specializing in spicy and exotic dishes, mead, and adventurers). The Pixie’s Kitten is Sandpoint’s only brothel, but its sense of style and panache belies the rural environs.

== Goblins

Goblins have lived along the Lost Coast for as long as anyone can remember, but that certainly doesn’t mean they’re welcome. Viewed as pests by most and monsters by all, goblins’ reliance on the garbage of greater societies has ensured their simpering, cavorting proximity to better civilizations since the start. Goblins are naturally craven, gleefully foolish, and ever eager to visit atrocity and pain upon those they encounter, a combination that one might think would have led to their eradication by their betters long ago. But goblins are fecund and stubborn if nothing else. Much to the distress of the rest of us, goblins are here to stay.

== Sandpoint Devil

They say it’s bad luck to see the Sandpoint Devil—that it’s the son of a widow who brokered a deal with a devil to gain a child, and that it stalks children and snatches them from their beds through windows left foolishly open. They say the beast is so hideous that even drawings and pictures of the fiend are prone to bursting into flame. That the Sandpoint Devil actually exists is not debated—it’s been sighted by too many reputable folk, and savaged too many innocent victims to be compeltely a myth. Rumors abound as to its lair and its genesis, but the Devil itself is very much a real creature—flesh and blood and smoke and fire and all.
