= Fires Over Brinestump

link:../../index.html[Home] » link:../index.html[Jade Regent 2020] » link:index.html[Story Journal]

This adventure begins in the town of Sandpoint with reports that the Licktoad goblins of Brinestump Marsh have grown unusually aggressive. The reason for this uncharacteristic bravery seems clear—the goblins have somehow managed to arm themselves with what appears to be a considerable supply of fireworks. The problem stems not so much from the additional "`firepower`" these fireworks provide as from the inflated sense of ego and power that the devices have given the goblins—the fireworks have made them dangerously brave.

Several merchant caravans and travelers have been attacked so far, and according to the victims, the damage caused by horses panicking at the sight and sound of exploding pyrotechnics is almost as destructive as the goblin attacks themselves. With the last few attacks resulting in severe injuries to three unfortunate travelers, the problem has escalated from an annoyance to a threat. However, as none of the attacks have yet inconvenienced Magnimar (only Sandpointers and other Lost Coasters have been hit so far), the city has been slow to react. Unwilling to idly sit by and wait for the goblin problem to escalate to actual deaths on the Lost Coast Road in order to attract Magnimar’s attention, Sandpoint’s leaders have put out the call for goblin exterminators.

But after a time of upheaval a few years back involving goblins, giants, and even a dragon, Sandpoint has since returned to being a relatively sleepy town. It doesn’t take long for life to settle down once things return to normal, and with Varisia’s adventurers now more eager to try their luck at finding their fortunes in legendary Xin-Shalast, there simply aren’t a lot of volunteers to fight goblins around. Always running at a lean enrollment, Sandpoint’s city watch can’t afford to send patrols into the trackless expanse of Brinestump, although they have stepped up their presence along the Lost Coast Road itself. The task of wading into the notorious local wetland falls instead to adventurers—be they concerned locals honestly eager to aid the town or greedy mercenaries looking to make relatively easy coin. A few adventurers have already made the attempt, but nothing has been heard of them in the 3 days since they entered Brinestump Marsh, and just last night, another round of colorful explosions burst over the wetlands south of Sandpoint. The goblins are doubtless readying a new attack!

To deal with the goblin threat, Sheriff Belor Hemlock has restored Sandpoint’s old "`goblin bounty`" after several years of inactivity—it was suspended when a group of eager but too-young adventurers were swept out to sea while in pursuit of goblin ears. The town of Sandpoint will pay 10 gp for every relatively fresh goblin ear delivered to the town hall—with an additional reward of 300 gp for the group who can bring in the head of the Licktoads’ leader, Chief Gutwad.

Brinestump Marsh may not be as large as the Mushfens farther to the south, but the swamp is dense and tangled. It’s easy to get lost in the place. No one’s made a really detailed map of Brinestump—there’s been no need, since there’s not much of value within. But if anyone knows his way around in the marsh, it’d be that old eccentric halfling Walthus Proudstump, the self-appointed "`warden`" of the swamp. A fishing trail leads from the Lost Coast Road directly to Walthus’s shack in the swamp.

== Into the Marsh

Brinestump Marsh is a relatively small region, but it’s fantastically overgrown with vegetation. Given the frequent stretches of muddy bogs and snaking waterways, moving through the marsh is a tiring and frustrating procedure. The marsh itself is bounded on its southern edge by a cliff that rises an average of 40 feet from the wetlands below to the moors above—characters who take the time to scout out this southern approach can get a relatively good view of the marsh and its major waterways, but spotting details (such as individual buildings) is quite difficult, because of the height of the trees that grow so thickly in the wetland.

Brinestump Marsh extends just over 2 miles at its widest point (measuring from the southwest to the northeast). The wetland is a tangle of nettles, reeds, and other swamp plants often supplemented by larger vegetation—cypress, eucalyptus, oak, and willow trees mostly. The aptly named Soggy River is the primary waterway that flows through Brinestump. The river averages 20 feet deep, while its smaller creeks average 5 feet deep.

The swamp is a frightening, oppressive place. Though small on a geographic scale, the marsh is fecund and spooky. Fog often shrouds the place, particularly at dawn and dusk, and animal calls that might be soothing elsewhere take on a strange, almost menacing tone in the dripping wetland. Sudden movement in the underbrush or in the tree canopy above, the splashing of something large wading through the swamp just out of sight, and eerie low growls and bellows from deeper in the swamp keep visitors on their toes.

== The Soggy River Monster

For the past 3 years, fishermen and farmers have told stories of a pale monster with legs that bend like a dog’s, that dresses in rags, and that hunts along the shores of the Soggy River. Sightings of the so-called "`Soggy River Monster`" are most common near Brinestump Marsh, causing most to believe the creature dwells somewhere in the swamp. The creature has been blamed for at least five disappearances over the past year, although Sandpoint’s militia suspects these disappearances are, in fact, simply bored sons and daughters running away from home to seek an exciting life in Magnimar.

== Walthus Proudstump

Walthus Proudstump, halfling ranger and self-avowed snake wrangler, has lived in the Sandpoint hinterlands for nearly 5 years, but none in Sandpoint can rightfully claim to know the near-hermit. Walthus likes to think of himself as retired after a short but excessively dangerous adventuring career in which he and several other halfling slaves abandoned a sinking Chelish merchant ship bound for Nisroch. Walthus chose to flee north along the coast on his own, and by the time he reached Sandpoint he’d had quite enough of adventure. He’d also had enough of city life, and spent nearly all of the money he’d made on his adventurous trek north to purchase an old building, sight unseen, in Brinestump Marsh. The scam artist who sold Walthus the old building walked away from the deal thinking he’d gotten the better of the halfling, but in fact, Walthus knew exactly what he was paying for—isolation and a place to hide from any Chelaxians who come north looking for escaped slaves.

Walthus spends most of his time fishing, patrolling the relatively small "`island`" his home is located on, and tending to his collection of snakes. The latter factor, more than his reclusive lifestyle or lack of personal hygiene, is the primary reason so few come to visit the halfling. Walthus understands this, and sees it as a welcome side effect of his love of serpents.

== Licktoad Village

A filthy village-fort surrounded by a crude wooden palisade sits atop a low hummock of solid ground here. A wooden gate in the north wall of the palisade lies in shambles on the ground. Nearby, a large, algae-filled pool on the northeastern side breaks the palisade and allows a clearer view into the village’s interior, which consists of a collection of ramshackle huts connected by wooden walkways, all built on thick wooden stilts.

This crude village is the home of the Licktoad goblins, the smallest of the numerous goblin tribes in the Sandpoint hinterlands. Historically, the tribe’s small size has kept them from joining in the time-honored pursuit of raids on human settlements—the majority of the Licktoads’ triumphs have normally come from scavenging from the swamp itself, a pursuit that is as dangerous for goblins as for most other explorers of the treacherous wetland.

== Brinestump Caverns

A fifty-foot-high cliff rises along the marsh’s southern border, its face a thick tangle of jutting rocks and bright green vines and nettles. A curtain of these thick nettle vines partially conceals a cave opening at the base of the cliff.

When the Kaijitsu fleet ran into trouble on their hasty return from Brinewall 24 years ago, two of the ships were driven toward shore while the third was swept out to sea. The crew of the two ships that ran aground (the Kaijitsu’s Blossom and Kaijitsu Star) sheltered in their wrecked, half-flooded ships for several hours before meeting very different fates. As the storm worsened, those who had survived the wreck of the smaller Kaijitsu Star drowned. Recognizing this exact danger, the survivors of the Kaijitsu’s Blossom decided to gather the greatest treasures from their ship’s hold and risk an overland flight. Staggering away from the shore through the storm-lashed swamp, they came to this cave entrance.

Today, these caverns serve as the lair of the fallen samurai Tsutamu and his undead soldiers—compelled only by their shame and anger, they remember little of their lives before. They want only to guard their treasures until destroyed. If left to fester for much longer, the wrath fueling Tsutamu and his soldiers will eventually compel the skeletons to begin stalking larger and larger surrounding areas, eventually making them a threat to the Lost Coast Road and, if not stopped, a danger to Sandpoint as well.
