= Ruins of Brinewall

link:../../index.html[Home] » link:../index.html[Jade Regent 2020] » link:index.html[Story Journal]

The colony of Brinewall was founded over 250 years ago in 4442. Construction on Brinewall Castle began soon thereafter, but funding problems and several disasters along the way slowed construction to a crawl. The worst disaster to strike occurred when the castle’s partially completed eastern wall collapsed into a cavern network below. Hideous demon-worshiping creatures known as dire corbies emerged from the now-exposed cavern complex to attack the colony, and final construction on castle was not completed until 4469.

After Magnimar was founded in 4608, Brinewall finally began to come into its own—trade picked up, and several important and powerful merchants, among them the Kaijitsus, took an interest in helping the town grow. But Brinewall never saw the success that visited Korvosa, Magnimar, and Riddleport, and finally fell to an enemy more swift and efficient in dealing death than the dire corbies, Nolanders, and Linnorm Kingdoms raiders combined. An unknown force, swept in and slaughtered the entire population of the small village during a terrible storm. They then overran the castle itself and finished the task of slaying every resident within.

As the caravan approaches Brinewall, the oppressive feeling of the place is impress upon them. The track they’ve been following all this time passes about half a mile east of Brinewall, continuing north and crossing the Steam River into the Nolands over a weathered wood-and-stone bridge. An old signpost about a hundred yards south of this bridge reads "`To Brinewall,`" and points down an overgrown trail that winds through a forest. This track quickly fades away entirely into the undergrowth, and further progress toward the ruined village must be made on foot.

Unfortunately for Ameiko, however, exploration of Brinewall is not in the cards. As the caravan near Brinewall, Ameiko grows more and more listless and sickly. She tries to hide her condition, figuring she’s simply exhausted from the long journey or that she ate something that disagrees with her, but as they reach the end of the road and prepare to explore Brinewall, how pale and shaky she looks becomes apparent. A few moments later, she collapses to the ground, unconscious.

If she’s taken farther away from Brinewall, her body begins shaking as if undergoing a fit. Eventually she begins screaming in her sleep and thrashing with increasing violence. These fits immediately cease if Ameiko is allowed to remain motionless and isn’t taken farther away from Brinewall.

Sandru, Koya, and Shalelu agree that whatever is causing Ameiko’s coma likely has something to do with the Kaijitsu legacy hidden somewhere in Brinewall. Although she’s unconscious, Ameiko seems to be sleeping peacefully. For now, the three are content to remain at the caravan to guard and protect Ameiko while the heroes head into Brinewall to attempt to solve the mystery of what’s afflicting their friend.

== Cemetery

A rickety wooden fence surrounds the clearing beyond, but the gates here are made of iron and flanked on either side by statues of a beautiful woman with butterfly wings, depicting the goddess Desna. This clearing consists of a low hill containing nearly two dozen graves. A stone crypt sits atop the hill to the east. The entire graveyard is unusually well tended—the grass appears to be weeded and the gravestones are quite clean. The crypt contains only one body, that of Admiral Mercatio Kiameleu, Brinewall’s founder. What appears to be a gravestone set apart from the rest of the graves near the northern edge of the cemetery is in fact a small, well-tended shrine to Desna that consists of a marble statue of the deity holding aloft a small copper bowl. Although worth 25 gp, as long as the bowl is left in place, any water poured into it automatically becomes holy water. The bowl can perform this minor miracle once per day. When the PCs first arrive, the rainwater in the bowl has already been blessed in this manner. The bowl can hold 3 flasks’ worth of holy water at a time, and is currently full. The lyrakien Spivey (see below) lives in this graveyard.

== Spivey

Brinewall’s oldest resident—a tiny, butterfly-winged azata—came to the region nearly 10 years ago and has been lurking in the area ever since. This azata is a lyrakien cleric of Desna named Spivey, long stranded on the Material Plane after her mistress was slain by a "`hungry plant`" (actually a giant flytrap). After several months of aimless wandering, Spivey came upon the ruins of the church of Desna here and took it as a sign. She originally tried to rebuild the temple, but gave up when she started attracting the wrong kind of attention from the denizens of the castle. Instead, she’s taken to living in the cemetery, where she does her best to keep the graveyard clean and free of undead and other desecrations. The inhabitants of the castle aren’t really sure what Spivey is—she’s quick to stay hidden when they come looking for her—but many of them have tasted her magic, and thinking she’s a ghost haunting the graveyard, they leave her alone.

Spivey’s eager to find out what the newcomers are doing in Brinewall. She encourages them to try to clean out the castle, and while she won’t accompany them, she does explain how the holy water font in the cemetery works, and offers them use of the cemetery as a place to rest in between forays into the castle, promising them free healing whenever they need it. Spivey is reluctant to abandon the area as long as the dire corbies and other monsters dwell in Brinewall Castle.

== Brinewall Castle

Brinewall Castle is a large and intimidating structure. Although only two stories tall (with the exception of one three-story tower and the dungeons beneath it), the squat castle looks all the larger for its position atop the bluff west of the village, looming over the surrounding region with a commanding presence. The castle is built of gray stone, though close inspection reveals numerous different types of stone were used in its construction (as parts of the castle were rebuilt several times). The castle’s curtain wall is 15 feet high with numerous arrowslits, allow its denizens a commanding view of the castle approach.

== The Brinewall Mystery

Briefing Room:: A large table lies in shambles in the middle of this room, while crumbled suits of armor bearing decorations of dragons twisting around castle towers lie in heaps along the walls. A flight of stairs winds up along a curved wall to the north. The air in this room feels stuffy and carries an eye-watering reptilian stink. Although the room is in disarray, there are a number of documents, maps, and troop lists that date back to the night Brinewall was attacked. This room has sheltered the documents somewhat, but they’re still damaged. All that can be pieced together from the documents here is the fact that the guards believed that the citizens of the village below were rioting, and that several of the buildings had caught on fire. They were preparing to mount an expedition to investigate and bring order, but there is no indication of their success or failure.
Tower Guardposts:: These cramped rooms contains several old crates and barrels covered with thick layers of dust. Once used to store arrows, torches, and other supplies, these cramped rooms are all abandoned now. Ladders and trap doors in the ceiling of each tower lead up to the guard towers above. Spilled arrows, old bloodstains, dropped (and long since ruined) longbows, and the like, indicate that some massive battle took place here long ago.
Ballroom:: This large circular room features a ring of pillars that support a balcony just over fifteen feet above. A flight of stairs winds up to the balcony along the southern wall. Faded paintings of dancing elves decorate the walls, spattered here and there with ancient bloodstains. A terrible battle took place here long ago, and at least one of the aggressors in the fight possessed prodigious strength, judging from the deep gouges in the walls near the largest bloodstains (the gouges appear to have been created by an enormous axe or similar weapon in several places).
Servants’ Quarters:: The door to this room is stuck shut, and it hasn’t been opened in years. Filaments of white, fibrous mold grow all along the walls and across the bunk beds in this room, giving the room a foul, musty stink. Here and there, thicker mounds of fungus grow in nauseating colors. The fungus-covered corpses of the servants here are among the few existing remains of the castle’s original doomed inhabitants. Although only a few bones are left, an investigation of them (once the mold’s cleared away) reveals limbs and heads severed by sharp slashing weapons, and no sign of skulls (these were taken as trophies).
Captain’s Office:: The officer’s desk and the chairs that once decorated this room lie in shambles on the floor. A flight of stairs leads up to the southeast. The battered door to this room hangs askew, revealing a short hallway beyond. There are several scattered and hastily written notes among the desk’s shambles, one of which is part of a letter mentioning an attack on Brinewall Castle. The letter describes the attack as a night assault by men dressed in dark robes. The letter is unfinished and contains no further information.
Storeroom:: The denizens of Brinewall avoid this room, and the door is stuck closed. The sounds of a young child sobbing can be heard coming from the room beyond. Although this storeroom may have once been well organized, the fallen crates and broken barrels that fill the room now present a tangle of debris. A young boy's skeleton is found, still pinned to the floor beneath a stack of old firewood and a heavy iron brazier. The child had tried to distract himself from the sounds of battle outside by scribbling drawings on the wall with charcoal—these images depict crude representations of ninja with throwing stars, frightening bird-headed men, and lumbering magical ogres wielding axes—images made all the more frightening by their childlike quality.
Haunted Donjon:: Old tapestries depicting a seaside castle hang askew on the walls of this circular room and a thick layer of dust cakes the floor. The air is musty and weirdly cold. Old bloodstains splatter the walls, along with numerous brutal gashes and slashes to the stone itself. Two doors hang askew on hinges in a passageway to the south, while to the north, a third door lies in fragments on the floor, opening onto a flight of stairs leading down into darkness. A second staircase leads upward against the north wall. This room still carries echoes of the final horrific moments and overwhelming despair of the soldiers who fell here. The slaughtered spirits remain as a haunt, a traplike manifestation of despair and horror. This haunt is particularly focused near the stairs leading down to the vault, where the last few soldiers died.
Brinewall Vault:: The walls of this room are of smooth stone, spattered with ancient bloodstains and deep, violent gouges. Deep drifts of dust lie on the floor, while immense stone doors hang open to the southwest, revealing empty vaults beyond. Brinewall’s last two defenders were slain here. While the invaders took Brinewall’s commander, Andril Kortun, back upstairs to  and transformed him into a wight, they chose to despoil their greatest enemy here where he fell. Rokuro Kaijitsu’s body is long gone, but his spirit remains bound to this vault in the form of an insane and enraged wraith.

== Kelda Oxgutter

Kelda Oxgutter is the only survivor of a raiding party that came to loot Brinewall of its treasures. She remained convinced of her chances for success even after her shield-brothers died in a battle against a sea drake because she’d come across a partial and early plan for Brinewall castle that showed the location of a secret entrance. She hoped to use this entrance as a direct route to Brinewall’s treasury, but unfortunately for her, the entrance led instead to the lair of the most dangerous creature dwelling in the caverns below the castle. She was quickly captured and turned over to Kikonu by the denizen. The oni has imprisoned her in the northern cage here while he decides what to do with her.

Kelda is ashamed of having been captured. She stands in her cell, dressed in rags but silently defiant. Normally a woman of few words, she’s particularly closemouthed about how and why she became imprisoned. She’s lost interest in Brinewall’s treasure, and wants only to leave.

== Visions of Jade

The Amatatsu Seal is a potent artifact, one capable of altering destiny and changing the course of nations. When the heroes first open the warding box that contains it, the Amatatsu Seal immediately marks each hero as an agent of the family, turning them into Amatatsu scions. In addition, the heroes momentarily black out and experience a rapid series of visions.

In the visions, the heroes see an army of terrible fiends—with burning skin, glaring eyes, and sharp tusks, wearing strange armor and wielding exotic weapons—emerge in a storm from a vast forest, then descend upon a nation populated by Tian people. This vision is swiftly followed by another: a young man dressed in royal robes stands over a simple well, a friend at his side. Suddenly, the friend grows nearly three times in size and is sheathed in a frightening suit of jade armor. The jade warrior draws a sword and strikes down his royal friend, then holds the bloody sword aloft in triumph. A third vision follows, this time of a young Tian man handing a beautiful sword to a richly dressed Ulfen man in exchange for a bag of gold. Finally, this vision fades, and the heroes see their friend Ameiko waking from her deep sleep, but she is dressed in the finery of an empress. She rises from sleep not in a humble Varisian caravan, but from a resting spot within the arms of a jade throne.

These visions pass in the span of a few heartbeats, and after they do, they impart knowledge to the heroes’ minds. They know that the land they saw invaded by fiends was Minkai, that the man they saw murdered by the jade warrior was Emperor Shigure of Minkai. They know that Ameiko Kaijitsu’s true family name is Amatatsu, one of the five royal families of Minkai—indeed, the last surviving royal family. The heroes recognize the young Tian man with the sword as Ameiko’s grandfather, Rokuro Kaijitsu, formerly Amatatsu Tsutoku, selling the family’s legendary sword Suishen to the Ulfen merchant Fynn Snaevald in the city of Kalsgard to finance his family’s flight and exile. They also know that Suishen is intelligent, and can impart much more knowledge of the Amatatsu family’s legacy if recovered. Further, they know that Ameiko herself is the heir of her line. Finally, they know all of the powers and abilities of both the Amatatsu Seal and its warding box—including the danger of leaving the warding box open, which would allow the oni of the Five Storms to once more track the Amatatsu Seal.

Back at the caravan, Ameiko experiences these same visions, and as they pass, she wakes with a gasp as the kami possessing her returns in a flash back to the Amatatsu Seal. She quickly recovers from the ordeal, and like the heroes, may be a bit overwhelmed at what the visions revealed, but with the passing of a few days, she is eager to travel to Minkai to seize her birthright and save an empire.
