= A Darker Road

link:../../index.html[Home] » link:../index.html[Jade Regent 2020] » link:index.html[Story Journal]

== The Gates of Desna

On the second day the hungry storm engulfs the caravan, making travel slow and difficult and battering the caravan. It quickly becomes apparent that escaping or surviving the morozko’s onslaught will be extremely difficult, however after 3 days of searching through the storm for the Gates of Desna, the caravan reaches the shelter of the Path of Spirits, where it stops to repair the heavy damage from the storm.

The Gates of Desna are named for the statues of the goddess that flank the entrance to the necropolis between two arms of a rugged peak. One statue is broken off at the pedestal, but opposite it still stands a primitively carved statue of a woman with butterfly wings eternally facing north, with a roughly carved eight-pointed star graven into her forehead. A quarter mile beyond, a cave mouth yawns at the head of the valley, with a carved stone lintel and doorposts etched with faded stars: the entrance to the Path of Spirits.

The long, dark Path of Spirits is a trip of approximately 50 miles from the entrance at the Gates of Desna to the Uqtaal Necropolis. The ancient nomads delved only where necessary, following natural faults, rifts, and cave systems. The tunnel has many steep slopes and narrow passages that can be traversed by lone humanoids but are difficult to navigate with wagons. Because of the darkness of the path and the close quarters, the caravan moves at only half its normal speed.