= A Darker Road

link:../../index.html[Home] » link:../index.html[Jade Regent 2020] » link:index.html[Story Journal]

== The Gates of Desna

On the second day the hungry storm engulfs the caravan, making travel slow and difficult and battering the caravan. It quickly becomes apparent that escaping or surviving the morozko’s onslaught will be extremely difficult, however after 3 days of searching through the storm for the Gates of Desna, the caravan reaches the shelter of the Path of Spirits, where it stops to repair the heavy damage from the storm.

The Gates of Desna are named for the statues of the goddess that flank the entrance to the necropolis between two arms of a rugged peak. One statue is broken off at the pedestal, but opposite it still stands a primitively carved statue of a woman with butterfly wings eternally facing north, with a roughly carved eight-pointed star graven into her forehead. A quarter mile beyond, a cave mouth yawns at the head of the valley, with a carved stone lintel and doorposts etched with faded stars: the entrance to the Path of Spirits.

The long, dark Path of Spirits is a trip of approximately 50 miles from the entrance at the Gates of Desna to the Uqtaal Necropolis. The ancient nomads delved only where necessary, following natural faults, rifts, and cave systems. The tunnel has many steep slopes and narrow passages that can be traversed by lone humanoids but are difficult to navigate with wagons. Because of the darkness of the path and the close quarters, the caravan moves at only half its normal speed.

Over the course of several days the heroes’ caravan fights it’s way through undead, magical barriers and a tribe of yeti. Choosing not to disturb or rob the graves of the dead the heroes make their way through the necropolis to a large cavern on the far side where they are beset by an angry mob of yeti. The heroes manage to drive off the yeti, but in the fight the caravan’s horses are injured, frightened off or killed and wagons damaged to the point of un-useability. With more yeti sighted ahead and one of the heroes near death, Ameiko calls for a retreat and suggests finding a defendable place in the necropolis to recover.

Choosing to heed Ameiko's advice, the heroes retreat to a defensible corner of the necropolis for the night which passes without incident. Returning refreshed to the battleground the next day, they find few remaining yeti, but upon defeating the yeti chief, Katiyana's ghost emerges from the corpse and rises above the heroes surrounding them in a small blizzard and taunting she can never be killed, that she has become Katiyana the Eternal, the Avatar of the Hungry Storm, Handmaiden of Sithhud, and the Harrower of All Creation. However our brave heroes are not dismayed and with some clever use of magic they bring down Katiyana's blizzard aura and fly up to battle her in the air. As before she blasts the heroes with lightning, but this time they are prepared for her tricks and take few injuries as they defeat her a second time. But will she rise again?

Victorious the heroes return to the wreck of the caravan to salvage what they can and then finally emerge to the surface once more where they are greeted by clear blue skies. Having been unable to salvage any wagons, it's a two week trek through the Wall of Heaven mountains on foot, but the heroes finally make it through the mountains and back to the Path of Aganhei. After 11 months passing over the crown of the world, they've finally entered Tian Xia also known as the Dragon Empires.