= The High Ice

link:../../index.html[Home] » link:../index.html[Jade Regent 2020] » link:index.html[Story Journal]

In the spring, almost 4 months since they left Kalsgard, the heroes have completed a long journey across the tundra but are reaching the farthest extent of regular human habitation. While hunters, hermits, and caravaneers sometimes foray onto the High Ice (the vast region of the Crown of the World covered by the polar ice cap), and a few brave (or mad) individuals venture near the true pole, there are few if any permanent settlements beyond this point. Ulf Gormundr suggests that the heroes avoid the primary caravan route that passes through the trade-town of Unaimo for the time being and instead journey to a cliff-village he knows of some miles to the west, called Iqaliat. Ulf possesses a tribal talisman made of remorhaz scales that is a symbol of friendship from the hearthmistress of Iqaliat and should guarantee them safe conduct. As it is the off season for travel across the Crown of the World, Ulf would like to get a better idea of the prevailing conditions from those he knows and trusts before deciding on the best path for the caravan to take.

== Iqualiat

The village of Iqaliat is a known safe haven built into the overhanging cliffs of Alasek Ridge, at the southern edge of the polar plateau known as the High Ice. During the summer melt, waterfalls by the hundreds pour down the icy cliff face for hundreds of miles to either side, but Iqaliat draws water year round through a subterranean stream that runs through cracks in the rocky schist of the cliff. Most of Iqaliat’s buildings are 10 to 20 feet tall, crafted of stone and clay brick fired in kilns during the warm season. Their outer faces are clad in harder rock cleaved from the schist, fitted with mortar or sculpted with stone shape cast by generations of shamans.

Arriving in the Erutaki village of Iqaliat, the heroes learned that morozkos (strong unnatural blizzards) block the Path of Aganhei to the east and a dragon was threatening the village from the north, blocking that path. They were then accosted by angry villagers led by the shaman Tunuak who was suspiciously accusatory of the heroes and the village leaders. The heroes and the friendly hearthmistress managed to diffuse the situation slightly and were asked to leave the village. With no other course of action seemingly available, the heroes proceeded to the dragon’s lair, learned the reason for it’s attacks and were forced to kill it in self defense. Returning to the village with the dragon’s head as proof, they were welcomed as heroes and the village began preparing a feast to celebrate their victory over the dragon. While preparations were underway, the heroes proceeded to show the chief, the evidence they uncovered indicating someone from the village destroyed the dragons eggs, angering it. With the chief the heroes went looking for the shaman, hoping he could divine the owners of the items recovered, but he was not in his tower, nor at the alter where his assistant suggested looking. His assistant also mentioned that he too once went looking for the shaman, having watched him enter the tunnel to the alters, but when the assistant entered, he could not find the shaman. Searching the tunnel the heroes find a trapped secret door leading to a secret shrine to Sithhud (the demon lord of blizzards and the frozen dead) beneath the cliff where they find and defeat Tunuak. Fragments of white dragon eggshells found there identify the shaman as the one responsible for the dragon’s attacks and pictograms along the walls depict black standing stones, morozokos devouring Erutaki villages, a blue-skinned woman with dark wings and hair and the Nameless Spires. The Erutaki explain the Nameless Spires are to the north and where the Erutaki believe the wind spirits reside. They are a dangerous place but a source of great visions for those brave enough to seek it. Tunuak himself undertook a vision quest within the last year; most likely he fell under the spell of this unknown winged woman.
