= The High Ice

link:../../index.html[Home] » link:../index.html[Jade Regent 2020] » link:index.html[Story Journal]

In the spring, almost 4 months since they left Kalsgard, the heroes have completed a long journey across the tundra but are reaching the farthest extent of regular human habitation. While hunters, hermits, and caravaneers sometimes foray onto the High Ice (the vast region of the Crown of the World covered by the polar ice cap), and a few brave (or mad) individuals venture near the true pole, there are few if any permanent settlements beyond this point. Ulf Gormundr suggests that the heroes avoid the primary caravan route that passes through the trade-town of Unaimo for the time being and instead journey to a cliff-village he knows of some miles to the west, called Iqaliat. Ulf possesses a tribal talisman made of remorhaz scales that is a symbol of friendship from the hearthmistress of Iqaliat and should guarantee them safe conduct. As it is the off season for travel across the Crown of the World, Ulf would like to get a better idea of the prevailing conditions from those he knows and trusts before deciding on the best path for the caravan to take.

== Iqualiat

The village of Iqaliat is a known safe haven built into the overhanging cliffs of Alasek Ridge, at the southern edge of the polar plateau known as the High Ice. During the summer melt, waterfalls by the hundreds pour down the icy cliff face for hundreds of miles to either side, but Iqaliat draws water year round through a subterranean stream that runs through cracks in the rocky schist of the cliff. Most of Iqaliat’s buildings are 10 to 20 feet tall, crafted of stone and clay brick fired in kilns during the warm season. Their outer faces are clad in harder rock cleaved from the schist, fitted with mortar or sculpted with stone shape cast by generations of shamans.

Arriving in the Erutaki village of Iqaliat, the heroes learned that morozkos (strong unnatural blizzards) block the Path of Aganhei to the east and a dragon was threatening the village from the north, blocking that path. They were then accosted by angry villagers led by the shaman Tunuak who was suspiciously accusatory of the heroes and the village leaders. The heroes and the friendly hearthmistress managed to diffuse the situation slightly and were asked to leave the village. With no other course of action seemingly available, the heroes proceeded to the dragon’s lair, learned the reason for it’s attacks and were forced to kill it in self defense. Returning to the village with the dragon’s head as proof, they were welcomed as heroes and the village began preparing a feast to celebrate their victory over the dragon. While preparations were underway, the heroes proceeded to show the chief, the evidence they uncovered indicating someone from the village destroyed the dragons eggs, angering it. With the chief the heroes went looking for the shaman, hoping he could divine the owners of the items recovered, but he was not in his tower, nor at the alter where his assistant suggested looking. His assistant also mentioned that he too once went looking for the shaman, having watched him enter the tunnel to the alters, but when the assistant entered, he could not find the shaman. Searching the tunnel the heroes find a trapped secret door leading to a secret shrine to Sithhud (the demon lord of blizzards and the frozen dead) beneath the cliff where they find and defeat Tunuak. Fragments of white dragon eggshells found there identify the shaman as the one responsible for the dragon’s attacks and pictograms along the walls depict black standing stones, morozokos devouring Erutaki villages, a blue-skinned woman with dark wings and hair and the Nameless Spires. The Erutaki explain the Nameless Spires are to the north and where the Erutaki believe the wind spirits reside. They are a dangerous place but a source of great visions for those brave enough to seek it. Tunuak himself undertook a vision quest within the last year; most likely he fell under the spell of this unknown winged woman. The clues found in Tunuak’s Bore point to the Storm Tower, one of the "`Nameless Spires`" created by some ancient race in ages past, though standing about 150 miles from the Nameless Spires that loom atop Golarion’s North Pole.

== Across the High Ice

The journey from Iqaliat to the Storm Tower is 700 miles across the High Ice and into the Boreal Expanse, bearing north and west of the Alabastrine Peaks rather than following the Path of Aganhei eastward. Ulf has never been that close to the pole before, but he has heard stories and seen enough maps that, using the mountains as a landmark, he is confident in his ability to bring the caravan there, and afterwards guide it beyond the far end of the Alabastrine Peaks to rejoin the Path of Aganhei at Dead Man’s Dome.

Traveling across the High Ice is more difficult than the tundra, both because the terrain is more rugged and because it is more desolate, and thus harder to navigate. The environment also becomes more extreme the
farther north the caravan ventures. One hundred miles north of Iqaliat, the elevation passes 5,000 feet, subjecting the heroes and their caravan to altitude sickness. In the thin air at this altitude, the caravan becomes fatigued. At the end of 1 month, both the heroes and their caravan are considered acclimated to the altitude, and no longer suffer any adverse effects.

Extremes of light and darkness are also exaggerated as the caravan approaches the pole. At the heart of the midnight sun season, the sun remains fully risen and sheds its light all day and night, appearing to move in a circular pattern in the sky rather than rising and setting. This is treated as bright light during both the day and night.

After restocking and preparing for the journey and with the well wishes and assistance of the gratefull villagers, the heroes set out with their caravan heading north into the High Ice and ultimately the Boreal Expanse. The terrain and weather was harsh and barren but they encountered no active resistance on the journey to the Storm Tower.

== The Storm Tower

Nearing the tower the heroes were attacked by roaming groups of Hoarfrost Spirits. Thought little more than an annoyance to the brave heroes, each encounter served to reduce their strength and resources. The Storm Tower is a hexagonal spire of black basalt, towering hundreds of feet into the air. The tower is mired in a lake of black slush, with a shattered stone causeway leading across the lake toward a gaping hexagonal opening in the wall at the base of the tower. A huge, crackling ball of blue light floats just above the tower’s roof, while a raging white storm turns in an expanding spiral overhead. High winds endlessly encircle the Storm Tower. The remains of a great causeway of white stone leads up to the base of the tower, though it has long since succumbed to time and elements, leaving only a few ruined spans standing exposed above the black slush surrounding the spire.

A wide gap separates the end of the causeway from a hexagonal portal in the tower’s wall. Ambushed but not suprised by two four-armed creatures armored in dense, bony plates, the heroes quickly dispatch the threat. Inside the tower they are ambushed again by four Frost Wights, but the heroes prevail once more. Working together the heroes manage to activate a strange otherworldly crystal operated force-lift which rapidly takes them 100 feet up to the next level where they encounter an immense centipede-like beast with rows of chitinous plates on its back glowing red-hot. With skill and luck the heroes once again slay the immense beast quickly, but not without injury and they take a few minutes to recover.

Using the force-lift once again, the heroes rise to the third and final floor, a large room full of well thought defenses which serve to keep attackers at bay while the tower's master pummels them with supercharged lightning bolts. A difficult and frustrating battle ensues, taxing the heroes nearly to their limits, but with strength, luck and perseverance they overcome the defenses and defeat the lithe and graceful half-fiend sylph master of the tower. Upon her death the storm overhead breaks at once and the heroes’ caravan enjoys pleasant weather for a change.

== Dead Man’s Dome

Ameiko encourages the caravan to press on toward Tian Xia, and Ulf points out that they are now halfway to their goal, and their road to Minkai will be far easier without half-fiend sylph’s evil forces on the prowl. His plan is to continue following the Alabastrine Peaks and then rejoin the Path of Aganhei at a landmark called Dead Man’s Dome, a relatively uneventful 500-mile journey across the bleak and barren landscape from the Storm Tower. As the caravan draws within 50 miles of Dead Man’s Dome, however, it soon becomes apparent that a small army of undead is forming around the caravan. Ulf suggests making a stand at Dead Man’s Dome, relating its legend.

This bald hill was once a mighty watchtower that overlooked the rolling descent of the polar ice toward the tundra basin of Ruun Uvas, paid for by taxes levied upon merchant trains using the Path of Aganhei and sheltering under its protection. Two centuries ago, however, the tower and its grounds were attacked by an army of giants and undead. Many caravans were slaughtered, but a lone hero taken on as a guard led a charge that broke the enemy lines and then held off the enemy long enough to allow the surviving caravans to escape. The hero then fought his way back and, according to the tale, lured the enemy inside the tower and collapsed it upon himself and them. None knew his name, so those who marked the fallen tower as his cairn simply called it Dead Man’s Dome. While it still offers a commanding view of the surround, few willingly venture there during the dark night of winter, even though stories tell that the lone warrior still guards travelers who come there.

The caravan hurries towards the high ground of Dead Man’s Dome, but dozens of undead soon surround the caravan. True to the legend, the spirit of the Dead Man rises and begins to fight alongside the heroes to protect the caravan. While easily defeated, because of their numbers and distribution, some undead break through the defenses and damage the caravan. Afterwards the Dead Man returns to his grave, and after repairs the caravan continues the journey following the Path of Aganhei once more. For more than a month the caravan continues south towards Tian Xia, stopping to trade at Erutuki settlements and encampments along the way.

== The Last Pass

As the caravan approaches the Altan Zuud, also known as the Last Pass, the temperature steadily drops and ominous storm clouds dominate the southern horizon. As the caravan ascends toward the pass, the heroes clearly see storm clouds racing overhead, swifter than the wind, and hear a fell, feminine laughter mocking them from the clouds, interspersed with peals of thunder. The mountain peaks ahead are swallowed up in a roiling blizzard as avalanches cascade down the mountain faces to block the pass. Katiyana has returned, and the full fury of the morozko has been unleashed. The blizzard’s fury seems restricted to the pass itself, for the moment at least, but the morozko is still a storm—it is not a monster that the heroes can fight, any more than they can fight a hurricane.

Ulf and Shalelu offer suggestions for evading the storm, however Koya's suggestion is chosen. She has
studied the history of Desna’s worship in many cultures, past and present. She recalls the account of a traveler from long ago who traversed the Crown of the World and spoke of the Uqtaal clans—tundra nomads who worshiped Desna as the Queen of the North Star, their guide and protector in the long arctic night. The Uqtaal believed that souls sought to follow the North Star even in death, and through long years they excavated a subterranean necropolis within caverns at the feet of the Wall of Heaven. Beyond the stony tombs of the fallen, the Uqtaal carved a passage—called the Path of Spirits—for the souls of the dead to make their way onto the High Ice to follow the North Star to the top of the world, where Desna would carry them home into the stars. The account was hundreds of years old, but the traveler claimed the necropolis was very real and that he had found the northern exit of their tunnel, as wide as a highway, flanked by twin stone statues of Desna. By using the landmarks recorded by the traveler, it might be possible to find this pathway.