= Kalsgard

link:../../index.html[Home] » link:../index.html[Jade Regent 2020] » link:index.html[Story Journal]

Kalsgard, the trading capital and oldest surviving settlement of the Linnorm Kingdoms, is a huge, bustling city rising upon the southern shore of the Rimeflow River’s wide mouth. Founded countless centuries ago, it has grown from a crude village into today’s thriving metropolis. No records survive from the time of Kalsgard’s founding, but an ancient saga tells that King Ulvass set sail from Kalsgard on his epic journey to discover Arcadia almost 500 years before Aroden raised the Starstone from the depths of the Inner Sea. Therefore, the township of Kalsgard must have existed in some form for at least 5,000 years.

Historically, much of Kalsgard’s growth came from its role as a major trading port for Ulfen vikings returning from raids to the south. The spoils brought back by these reavers ensured the city’s expansion and allowed specialist crafts to develop that catered to the influx of sailors and local desires for exotic goods. In the more recent past, the rugged sailors of the Linnorm Kingdoms have increasingly turned to trade, making Kalsgard the primary mercantile port in the north. Much of the surrounding area consists of carefully tended farmland that generates foodstuffs and raw materials that are exchanged for high-quality merchandise and trade goods.

Kalsgard has been ruled by a continuous line of Linnorm Kings dating back to before the Winter War with Irrisen. While the city has suffered fire, siege, and other disasters, its citizens have always survived and rebuilt the city stronger than before. The Ulfen residents are a mixture of tribes from different parts of the northern lands, with subtly differing cultures and traditions. Other substantial human ethnicities in the city include the Varki, who come from the arctic lands of Icemark to the northwest; Varisians, who hail from the south; and Tians, who reside in the Jade Quarter along the city’s waterfront.

Kalsgard has a large dwarven population. Deeply integrated into the life of the city, dwarves are well regarded, and their expertise in many trades deeply appreciated. The lifestyle of Kalsgard suits dwarves; they mix freely with other races and are welcomed as valued members of society. While many dwarves hold respected positions throughout the city, a large number dwell in the enclave of Undercroft, a series of tunnels and canals built directly into the banks of the Rimeflow River and passing beneath the city itself. Here, among the foundations of Kalsgard, dwarves carve ice and stone to amass reservoirs of fresh water, and tend enclosures of underground livestock bountiful enough to provide for the city’s population during winter.

The gnomes of Kalsgard live primarily on the northern bank of the Rimeflow River in the township of Iceferry, operating many of the ferry services that provide passage across the river. There are also many who love the stimulation of living in the heart of Kalsgard. While some of the other citizens grumble at the gnomes’ eccentricities, many in Kalsgard feel they brighten the city, and enjoy their unique perspectives. The potent gnome whisky called throatburn is infamous throughout the city for its intoxicating power. On the first Fireday of Desnus, the gnomes of Kalsgard hold a mock "`Linnorm Hunt`" festival on the city’s main promenade. The hunt excites the imagination of Kalsgard’s children as they search for and "`slay`" the beast, an elaborate linnorm costume operated by gnomes and supplemented with illusion magic.

The natives of Kalsgard are used to seeing a wide variety of races and ethnicities on their streets. Visitors to Kalsgard find the native Ulfen coarsely boisterous and loud, but generally welcoming to those who treat the city and its people with respect and courtesy. While an exotically garbed stranger might draw stares from local passersby, these are almost always looks of curiosity rather than fear or hatred. The only exceptions are for those who openly present themselves as witches from Irrisen. The Linnorm Kingdoms have never formally declared a truce with Irrisen, and anyone foolish enough to claim to be an Irrisen national is swiftly arrested and then imprisoned, exiled, or executed.

*Government* overlord +
*Population* 72,080 (62,383 humans, 7,212 dwarves, 973 gnomes, 724 halflings, 493 elves, 83 half-elves, 212 other)
[horizontal]
Notable NPCs::
Linnorm King Sveinn Blood-Eagle +
War Priest Chief Gudrun Fire-Hair +
High Skald Thyrie Tarnralsdottir +
Master of Shipyards Sigfastr Gunnarsen +
Wind Sister Talla Yrsasdottir +
Royal Advisor Grundi Erigson

== Customs

All free warriors in Kalsgard are expected to own and bear arms. In the city, one of a leader’s duties is to provide his followers with weapons, whether that leader be a member of the ruling elite, a wealthy merchant, or a shop owner with a single employee. The fine armaments of a lord’s warriors enhance his reputation, and he would be ashamed to appear publicly with an inadequately equipped escort.

In Kalsgard, helms often bear flourishes in the shapes of wings, spikes, plumes, antlers, or even snakes; it’s considered bad luck, however, to wear a helmet with horns on it. Only in certain festivities or religious events is it appropriate to wear a horned helm. Often a play or a puppet-show portrays the villain or fool with a horned helm, and much comedy is made of the pointy headwear poking others or getting stuck in things like doorframes.

When an Ulfen citizen dies, mourners observe one of a wide variety of funeral rituals. If an Ulfen from a coastal, island, or river heritage dies and is wealthy or high ranking, mourners place the body aboard a simple funerary boat or raft for a final voyage and set the vessel alight as it is cast off, cremating the remains. For those whose ancestors came from settlements away from large bodies of water, an elongated circle of stones set in the ground symbolizes a ship, and the body is cremated upon a wooden pyre inside the circle. Those from places where wood is less available are inhumed in cairns or mounds, and richer folk are sometimes buried in wagons, along with the bodies of horses to carry them to the afterlife. A small rise to the south of the city holds many such mounds. Some of those from the southern Thanelands still bury their dead by sinking them into the peat bogs that lie to the southwest.

In almost every funeral ritual, the departed is dressed and outfitted for the journey to Pharasma’s domain. Workers and warriors have their weapons and equipment interred with them; homemakers, their domestic tools; nobles, their favorite jewelry; and so on. Food and drink are placed alongside the dead for the trip. It is said that in the distant past, funeral offerings even included the sacrifice of servants or captives so they could attend the departed in the afterlife.

== Law & Order

Given the volatile and competitive nature of many Ulfen and the sheer number of people crammed into the city, the justice system in Kalsgard is a mix of tradition and innovation that has evolved to suit the city’s circumstances. Many of the edicts created in Kalgard’s recent past were implemented to prevent or contain blood feuds. An example is an ordinance requiring aggrieved parties to wait 1 week "`for their blood to cool`" before initiating a blood feud. There are also efficient sets of regulations detailing how to arrange a suitable weregild as compensation.

There are few jails in Kalsgard; they are mostly used to hold suspects or put them into protective custody until their innocence or guilt can be determined. Those found guilty are usually required to pay weregild, or if they are unwilling to pay, are sold as thralls. Those convicted of serious crimes, such as betraying an oath to a liege-lord or cowardice leading to the death of allies, often receive sentences of thralldom, banishment, or a duel to the death.

The city of Kalsgard supports numerous guard troops. The city’s king maintains a watch independent of his own warriors, and each quarter has its own unit of guards. Most crafting and trading guilds retain detachments of security guards who patrol the streets in the neighborhood of guild buildings, and any important leader also has a retinue of personal bodyguards. Added to this is the law that obligates any adult citizen to aid in the capture of a criminal when a victim raises a cry. While Kalsgard has a reputation for brawling and fighting, as well as for locals who quickly issue challenges if they feel insulted, it is rare for visitors to have their pockets picked or be the victims of similar petty crimes. Even if such things happen, the culprit—who is often also an outsider to Kalsgard—is highly likely to be caught. A common punishment for stealing is shaving and tarring the thief. As a result, trifling crimes in Kalsgard are extremely unusual, and the few crime guilds that operate in the city are particularly wary and very cunning.

== City Geography

As Kalsgard has expanded over the centuries, the space inside the city’s walls has become overly cramped again and again. Each time the city runs out of room, its leadership embarks on massive projects to build extensions to the outer city wall. Visitors to Kalsgard might wonder why people don’t simply build new houses outside the city walls when the city becomes overcrowded. Yet being a warrior and raiding culture, the Ulfen want their homes securely defended, especially while they’re away. There are many tales told of the wilderness that exists just miles from the city, and the beasts that claw at the city gates at night.

The walls both around and within Kalsgard clearly divide the city, forming the boundaries of many of the city’s quarters. Remnants of older walls still exist in Kalsgard, but these were largely torn down long ago and their stones used as materials for housing. Today, the city’s soldiers and guards use the parapets of the remaining partition walls as a way to move swiftly across the city, and severe penalties are enforced for those found tampering with or pilfering stones from these ramparts. The walls converge at the great ring castle of Thanelands Linnorm King Sveinn Blood-Eagle, the center of city government.

== Amber Quarter

The Amber Quarter is the hub of manufacturing and production in Kalsgard. Shops with similar wares tend to congregate together along the streets of the quarter, making it easy for shoppers to compare items. All kinds of goods are available here, but the streets that bear witness to the most guards are those of the jewelers and crafters of precious metals. The people of Kalsgard love wearing jewelry to show off their wealth and rank. Men favor armbands and torcs, women tend to wear circular brooches and chain necklaces to fasten their tunics, and both sexes enjoy wearing rings and cloak pins. Swirling designs depicting monstrous creatures commonly decorate this jewelry. Many other types of objects including armor, buckets, combs, cups, keys, and weapons are also adorned with carvings or inlaid with valuable metals. Other precious materials commonly available in the quarter include mammoth and walrus ivory, jet, and pieces of amber. Artisans also create useful everyday items from inexpensive but unusual substances such as antlers, bone, and soapstone.

While most Ulfen use coins for purchases nowadays, in the past it was a widespread practice to create change during a transaction by chopping a piece of silver jewelry into pieces and valuing the silver by weight. Bits of this "`hacksilver`" can still be found in the quarter, and several shops specialize in collecting and rejoining pieces of hacksilver, or recreating missing parts of a valuable piece.

Recently, rumors have claimed that the Jade Serpent (a priceless idol brought back by some of the first Ulfen explorers to reach Tian Xia thousands of years ago) has resurfaced in the Amber Quarter. Such rumors have been circulating intermittently for years, and countless tales tell of those who find the ferocious linnormlike dragon statue, then lose it again as the destiny of the idol conspires to find its way back to Tian Xia.

== Bone Quarter

As one of the newest parts of Kalsgard, the Bone Quarter hosts more open space than any other quarter in the city. It is also one of the poorer and dirtier parts of the city. Many hopefuls who migrate to Kalsgard eventually find themselves here, as do most Varisian caravans visiting the region. The city’s residents see little distinction between travel-loving Varisian caravaneers and Sczarni con artists, and so prevent Varisian caravans from camping in any quarter besides the Bone Quarter without special dispensation.

The place was initially named for the cattle farmers and hunters who lived and worked here, but at present many in Kalsgard say that it’s called the "`Bone Quarter`" because you can see the ribs sticking out of the desperate and malnourished inhabitants. Accommodations and land are cheap, but the quarter is home to a large number of unemployed, and certain streets that run near the outer wall are dangerous to frequent after dark. Most houses in the quarter are cheaply made from branches daubed with a mixture of mud, straw, and dung, and have leaky thatched roofs. The neighborhoods close to Kalsgard’s center are full of humble, struggling families who work the lower-paying jobs in the city. They are most likely to suffer during winter, and there are always some in the Bone Quarter who succumb to starvation or die from illnesses throughout the harsh cold months.

Whispered stories claim that the rats inhabiting the middens and cesspits in this quarter have developed a sly intelligence and collective deviousness. Some claim that large packs of rats have been known to overwhelm animals and even brazenly devour people, but few reliable eyewitnesses have seen such unlikely horrors.

Deadeye’s Debris:: Named by destitute skalds living in the quarter, this charred ruin was once a towering wooden stave church of Erastil. Severely damaged after a fire tore through this part of the city, the temple’s priests abandoned the place 80 years ago. Today, the only inhabitant of the temple ruins is an old hermit named *Arnora the Ancient* who sees herself as the last guardian of the shrine. She protects it, preventing the townsfolk or anyone else from demolishing the ruins. Her powers and menacing appearance have given her a reputation for wickedness, but she sometimes provides healing to those who cannot afford to go anywhere else. Many in the quarter, however, would like to see her gone and the land cleared for new housing.

== Fire Quarter

Inland from the trading waterfront of Kalsgard is the rowdy Fire Quarter. Unlike most other parts of the city, multistory buildings are common in this quarter. Here all manner of Ulfen competition, relaxation, and entertainment takes place. While numerous wrestling halls and athletic courts provide places where one can engage in various athletic contests, taverns and drinking houses represent the most common diversions. The latter establishments host a diversity of boasting, brawling, dancing, and drinking challenges on a regular basis. Most taverns offer traditional drinking horns, but many customers prefer to use mugs and tankards, because unless entirely drained, a horn can’t be put down without spilling its contents. Every pub or drinking hole employs multiple bouncers, whose main tasks are preventing damage to the furnishings, extracting payment from those who do smash up the place, and directing groups of belligerent customers to an empty area where they can exchange blows without bothering other drinkers. The city guard patrols the streets in large groups, and unless it appears someone is about to be killed, they usually let brawlers resolve their grievances before dragging away the loser to recover in the guardhouse.

In many of the taverns, skalds entertain crowds with heroic sagas of champions from long ago. The high skald Thyrie Tarnralsdottir often performs at the Whistling Fox, and is equally famous in Kalsgard both for her poignantly beautiful sagas and traditional Ulfen kennings and for her unbeaten record in drinking competitions—thanks to a seeming near-immunity to alcohol. At the House of the Deep-Minded, the Ulfen board game of hnefatafl is popular. In hnefatafl, one player attempts to protect a leader piece from the other player’s larger army. Wagers between players and betting on games are common, and the house takes a small percentage in exchange for supplying the boards and venue. The taverns here cater to all tastes; at the Grim Harvest, for example, brooding regulars soak up the gloomy atmosphere and down bitter spirits from cups made from human skulls.

For those seeking paid companionship, a wide array of services are available, varying dramatically in price and quality. Asking for the best the Fire Quarter has to offer invariably leads to a visit to the Hall of Splendid Valor.

The Hall of Splendid Valor:: This is easily the finest and most expensive brothel in the city. Inside the hall’s doors, gorgeous "`azatas`" whose costumes consist of wings and little else escort patrons to an idealized (but inaccurate) version of a feasting hall designed to be similar to tales of Valenhall in far-off Arcadia. The clientele dine on sweetmeats and fine wines served by scantily dressed lovelies of their preference, while warrior beauties clad in impractical and extremely revealing armor perform mock sword and axe duels or wrestle for their audience’s pleasure. Customers then retire with their chosen escorts to luxurious fur-lined bedchambers. The keeper of the house is *Belende the Showy*, a sensual, wily, and amoral businesswoman willing to go to any lengths to drive her major competitors out of business and increase the profits of her bordello.

== Horn Quarter

The Horn Quarter is chiefly populated by farmers and laborers who cultivate the fields southwest of Kalsgard. Most farmers here grow small crops of vegetables near their homes to ensure that their personal stores can last through the long winter, and thick turf layers the roofs of their stone longhouses to provide insulation against the harsh clime. Superstitions abound among the Horn Quarter’s residents, who often make sacrifices of cattle, goats, or sheep to appease the gods and spirits, displaying the carcasses of such offerings on poles outside their front doors to show off their piety to neighbors.

The southern end of the quarter is home to a series of farms where beekeepers cultivate flowers during the warmer months and tend several colonies of a resilient breed of honeybee. About twice as large as a normal bee, specimens of this strain are also more aggressive but produce a clear, sweet honey that has its own unique taste and brews into excellent mead. Honey and beeswax from Kalsgard are highly regarded trade commodities throughout the Linnorm Kingdoms and in the nations to the south. Were it not for the value and wide-ranging appeal of these bees’ honey, the city’s rulers would never tolerate the bees within their city walls due to their frequent swarms, but circumstances being as they are, guards patrol the areas surrounding the apiaries to prevent tampering, watch for signs of swarming, and ensure no one is endangered.

The inhabitants of the Horn Quarter retreat inside the city walls before nightfall, normally having locked their animals in barns or sheds for the night. It’s rare for thieves or wild animals to break into a farmyard outside the city, but when this occurs, the farmers band together, often employing trained warriors to guard their properties during the night and catch the intruders.

The Stephfir Ostlery:: Situated close to the western city walls, this extensive series of corrals and stables gives the appearance of an upright establishment where riders can stable their mounts while in the city. It is also, however, one of the most popular venues in the Linnorm Kingdoms for the northern blood sport of horse fighting. Those leaving their mounts here should be clear with the staff what services they’re looking for—stabling or sport—or they might be surprised at their horses’ temperament when they return. At the Stephir Ostlery, trainers condition aggressive stallions to be wildly vicious toward other horses. Pairs of these horses are released into an indoor enclosure where they rear up, kicking and biting ferociously at each other, and battle to the death. While considered distasteful by many in Kalsgard, horse fighting remains a popular spectator sport, and the Ostlery’s fights draw large crowds who gamble heavily on the outcome. *Halldorr Byrakson* runs the stables. His current prize stallion, Duskgasher, is a brutal beast whose sharpened hooves have crushed the skull of many a challenger—both equine and human.

== Ice Quarter

The Ice Quarter is the focus of day-to-day commerce in Kalsgard, its crowded streets lined with a multitude of shops and stalls selling extravagances and mundane necessities to locals and visitors alike. Here fur-clad traders barter for consignments of trade goods in the many markets and merchandise is distributed. Close by Rannveig’s Run, the stream that runs through Kalsgard, looms the crenellated fortress-temple of Gorum, and the ornate and curving sky-shrine to Desna sits in the open courtyard by the quarter’s western gate.

Near the middle of the quarter rises a worn lump of stone roughly the size of a horse. The people of Kalsgard believe this to be the original runestone marking the founding of the settlement. While any markings have long since worn away, citizens often touch the stone for luck.

Numerous restaurants and eating halls have sprung up to accommodate visitors to the Ice Quarter; most of these establishments serve traditional Ulfen fare, including local delicacies such as grilled horsemeat and seabird stew. Several public bathhouses can also be found in the quarter.

The Hunting Serpent Inn:: This popular lodge welcomes all visitors to Kalsgard; its rates are inexpensive and its staff are happy to accommodate travelers with special preferences and exotic pets. The owner of the inn, *Tosti Finehall*, is one of a small congregation in Kalsgard that worships Cayden Cailean. Being a pious man, Tosti owns a rapier but never actually wears such a nontraditional weapon. Always glad to meet and talk with fellow worshipers, he only charges them a nominal amount for food and board.

== Ivory Quarter

Close by the shops of the Amber Quarter lies the business center of Kalsgard, where Ulfen merchants broker deals and backers organize trading expeditions and voyages. The city’s various trade guilds keep their guildhalls here. Some of the more powerful trading organizations in the city include the Seven Lands group, a syndicate that manages much of the trade between the seven kingdoms in the Lands of the Linnorm Kings; the Sunrise Seekers, a consortium that attempts long trading voyages to the south; and the Icecrown Union, the largest of the merchant guilds, which frequently sends caravans north over the Path of Aganhei to Tian Xia. The guildmaster of the Seven Lands group is *Hroldmar Ragnarson*, an extraordinary negotiator who heads an informal council of the trading guilds, and who works hard to balance their often-disparate interests, thereby preventing the guilds from turning against each other. He periodically requires the services of independent foreigners to complete tasks that must not be traced back to him.

== Jade Quarter

For generations, Kalsgard’s Jade Quarter has served as a home for the steady flow of Tian immigrants coming over the Crown of the World. Most hail from the empire of Minkai, and the Jade Quarter reflects many of that land’s native customs, architectural styles, and traditions, uniquely blended with the Ulfen ways of northern Avistan. Although most residents of the Jade Quarter are of Tian descent, the neighborhood also contains a sizable Varki population, composed of members of that nomadic group who find sedentary life to their tastes. Nevertheless, numerous intermarriages over the years and plenty of ongoing trade mean that a group of non-Tian folk walking down the streets of the Jade Quarter is nothing of particular note. Visitors, whether Tian or natives of the Inner Sea, often feel as though they’re entering an alien community when they happen upon the Jade Quarter, baffled by the bizarre intermingling of artistry, people, strict traditions, inscrutable faiths, and even the occasional rare creature, all buzzing amid the din of strange languages.

Madam K’s Perfumery:: While *Madam Kawaoh* knows an astonishing amount about fragrances and perfumes, this knowledge has absolutely no bearing on her business. Crammed into the basement level of a disreputable butcher’s shop, her tiny establishment appears to be a single room of shelves teeming with strange bottles and a riot of tear-inducing aromas. Few Tians and even fewer Ulfen visit her boutique, having neither the coin nor interest to indulge in such vanity. This suits Madam Kawaoh fine, though, as it disguises her actual work. Behind her miniature showroom lies an archive many times its size, filled with curiosities and exotica from across Tian Xia. Madam Kawaoh has made it her business to collect the relics and heirlooms many Tian immigrants are forced to sell after their long and dangerous treks to secure a place in Kalsgard. While she doesn’t return these items to their original owners, she tries to inform them of their treasures’ new home, giving them the first opportunity to buy the items back. Although these onetime owners can rarely afford to repurchase their former possessions outright, Madam Kawaoh knows the value of service and favors, and so has dozens of her neighbors indentured to her. Her secret shop is also open to those she deems worthy of exploring its treasures, as many of the items in her keeping are magical or quite valuable in terms of price and sentimentality. Non-Tian are rarely admitted, but she’s been known to show her wares to those who perform favors for her.

== Oak Quarter

The easternmost quarter in Kalsgard is the industrious Oak Quarter. Here booms of lumber brought downstream from villages and towns like Losthome are stored and crafted into a diverse assortment of finished goods. Burly laborers transfer logs from the river to lumberyards where workers saw them into manageable timber, which they sell to artisans throughout the city. A large number of woodcarvers, carpenters, and craftspeople live in the quarter, supplying the shipyards as well as producing furniture, carts, tools, cutlery, and diverse other merchandise. Wooden blocks pave many of the streets here, both to provide firm footing and to keep mud and snow from the shoes of residents. Several of the larger surface entrances to the Undercroft are located in and along the Oak Quarter’s riverfront. At the quarter’s northwest end stretches the Street of Winged Thorns, which features a series of shops selling well-made archery equipment.

The Guhailla clan, a family of crafters renowned for carving linnorm figureheads for new longships, resides in the Oak Quarter. Their carvings are exquisite works of art, and most Ulfen sailors consider a Guhailla figurehead to be both a status symbol and a good luck charm to protect them from disaster at sea.

Kalsgard Shipyards:: The shipyards are a chaotic series of piers, dry docks, and warehouses built seemingly at random along the Rimeflow’s edge. Owned by numerous family concerns allied together into the shipbuilders’ guild, the Kalsgard Shipyards produce the finest longships in the Linnorm Kingdoms. Kalsgard’s reputation for graceful, resilient, and swift longships often attracts sea captains from the other Linnorm Kingdoms seeking new vessels. The Master of Shipyards is *Sigfastr Gunnarsen*, a dwarf whose family has long resided in Kalsgard. With an innate affinity for woodcraft, Sigfastr journeyed to distant parts of Avistan to perfect the craft of shipbuilding. Having worked and studied in Eleder, Augustana, and other great shipbuilding cities, he returned home and quickly rose through the ranks of the shipbuilders’ guild. He hopes to personally craft the ship that King Sveinn will sail to Arcadia.

== Stone Quarter

The Stone Quarter rises upon a rocky incline east of the city’s center, and much of the stone used in the city originally came from here. At the center of the quarter stands a grand temple dedicated to the Forge Father Torag, surrounded by the workshops of many highly skilled blacksmiths and armorers. Traditional Ulfen society holds these artisans in high esteem, as historically Ulfen sea raiders trusted their lives to the quality of their arms and armor. As a general rule, the quality of smiths in the Stone Quarter corresponds to their shops’ proximity to the temple, and there is much competition among metalworkers to obtain land as close to the temple as possible.

There are also many learned residents of the quarter who study the history of their people, recording and passing on the traditional sagas and oral history of the Linnorm Kingdoms. While these scholars are far more scattered and informal than "`civilized`" academies, a patient and respectful pupil can learn a great deal from them. Numerous magic items can also be purchased in the various shops found here.

Stonemasons in the quarter chisel intricate and flowing designs into runestones. Most buyers commission runestones to remember dead kinsfolk or loved ones, to mark territory, or as longlasting reminders of historic events. A few older runestones in the quarter are known to hold mystical powers or forgotten knowledge.

The Great Temple of Torag:: From atop a knoll at the highest point in the quarter looms the imposing temple of Torag. Constructed from huge blocks of granite, the structure has the shape of an enormous warhammer, with the main worship area and holy forge at the hammer’s "`head`" and the "`shaft`" of the hammer housing the priest’s chambers. Elaborately etched steel paneling covers much of the interior, and highly decorated metallic bracing reinforces the vaulted ceiling. The high priestess is *Nauma Irongleam*, a hardworking woman also regarded as one of the foremost armorsmiths in Kalsgard. The spellcasting services but also occasionally needs the assistance of competent individuals to escort special shipments of ore from Kopperberget to the temple in Kalsgard.
