= Ecology of the Kami

link:../../index.html[Home] » link:../index.html[Jade Regent 2020] » link:index.html[Story Journal]

Kami are spiritual beings created by the gods and tasked with maintaining the balance of the natural world. This maintenance comes in the form of protecting the various creatures and things on the Material Plane that are often unable to protect themselves. Each kami has a particular “ward” that it watches over, such as an inanimate object, a plant, a creature, or even a region. Intelligent beings (such as most humanoids) and objects that exist outside of the natural order (such as undead creatures and constructs) do not have kami. One can predict the strength of a particular kami by the nature of its ward: A rock or frog kami may be a relatively impotent thing, but a redwood kami, a blue whale kami, or the kami of a mountain often exercises massive power. The vast majority of kami are good or neutral in alignment. Those rare kami who fall to evil—usually after failing their ward in some way—generally have their physical forms revoked by the gods, and are condemned to become wandering spirits who either perish in their aimless voyages or are pushed to become hateful and vengeful oni.

A kami forms an extremely intimate bond with its ward, melding with the object or creature the majority of the time and manifesting a physical body when it must protect the thing or otherwise chooses. A kami prefers its spiritual form more often than not, and assumes a physical form only when necessary, such as when it must communicate with mortals or shield its ward. While this manifestation leaves a kami vulnerable to death like any other mortal creature, the kami is almost always willing to make this sacrifice in order to protect its ward.

Not everything in the world has a kami, as there aren’t yet enough kami to represent every individual object, plant, and animal; filling this gap, however, is their eventual goal, and kami fervently spread themselves across lands in hopes of pairing every creation with a kami spirit. This grand design began in Minkai, and in the past several thousand years the kami have proliferated across much of Tian Xia. It is unclear exactly which regions the kami hope to expand into next, though they can potentially exist in any environment, and the other continents—including those of the Inner Sea region—are clearly viable options.

== Kami and Wards

The inanimate object, creature, plant, or region with which a kami is paired is known as its ward. A kami does not possess its ward and therefore does not control it. While the relationship between kami and ward is a deeply intimate one, it is perhaps more accurate to think of a kami as simply inhabiting its ward. Once attached to one another, the two develop a strong interdependence. A kami may leave its ward in either its spiritual or physical form, but the kami must eventually return to its ward to rejuvenate its strength, and while immensely powerful magic can be called upon to permanently separate kami and ward, nothing can break the mystical connection between them. A kami estranged from its ward for an extended period of time grows increasingly erratic; its powers wane significantly, and it is at serious risk of permanently losing its normally calm resolve, increasing the likelihood of the kami devolving into an oni. Wards whose kami have left them often show signs of premature aging or wear—animals become listless and appear ill, weak, or uncharacteristically skittish or aggressive; objects become brittle, lose their luster, or appear to wear down quicker; plants wither or lose their fragrance and potency; and regions slowly degenerate into dilapidated, ruined versions of their former selves.

Though kami are bound to defend their wards, this defense is always secondary to their defense of nature as a whole. Thus, a kami bound to a fox and a kami bound to a field mouse do not battle to the death when the former kills the latter. Predation, as well as death from old age, are part of the natural cycles laid down by the gods, and to end life in a matter fitting with one’s station is all any ward—or its associated kami—can ask for. A kami whose ward dies in such an honorable manner still suffers ill effects, but will often either die itself shortly thereafter and be reborn as a kami attached to a new ward, or else set out to find another (and usually similar) ward to guard—in the aforementioned example, perhaps as one of the field mouse’s offspring.

== Kami History

Created by the gods at the dawn of the Material Plane, kami were tasked with the sacred duty to multiply and shelter the gods’ creations. The gods also established a set of labyrinthine rules known as the Laws of Golden Perfection, which affect every aspect of the conduct of kami and their interaction with the world and its inhabitants. Beginning in Minkai (which accounts for their extensive presence in that nation), kami have spread all over Tian Xia in compliance with this divine directive.

A kami who falls from grace or fails its ward because of negligence is punished severely, and may lose its status as a kami if the offense is serious enough. Most fallen kami accept this terrible fate if it comes to pass, becoming purposeless spirits who lack the ability to interact with the Material Plane at all. However, those who come to resent their status, or those driven mad by their homeless misery, become oni, evil spirits in the flesh. Oni exist in endless conflict with kami, resenting them for the favor the gods show them and for what the oni see as their misguided devotion to the divine directive to shield creation. (See “The Ecology of the Oni” in Pathfinder Adventure Path #49 for more details on these vicious beings.) In contrast, oni see the world as a playground on which to indulge every base whim and desire that might cross their selfish and venal hearts. Though they often act in direct opposition to the kami, oni too must abide by the tangled and voluminous Laws of Golden Perfection, but the cruel beings do their best to bend and manipulate these strictures in their pursuit of physical pleasures. Kami and oni recognize one another on sight, regardless of the form each has taken. Kami find oni to be dreadful embarrassments, or live in fear that they may one day fail in their sacred responsibilities and become oni themselves.

== The Tayagama

This much-loved epic poem, written thousands of years ago by bards whose names have been lost to history, prominently features kami and oni. Like those creatures themselves, the poem has crossed numerous national borders throughout Tian Xia, becoming a shared touchstone for many different cultures. While comic exaggeration and hyperbole is its hallmark, the Tayagama also provides useful insight into both those mystical beings and the Tian peoples as a whole, as many varied cultural traditions often subtly tie back to the saga in some way. For instance, the most beloved of all kami presented in the poem is Teki, a fukujin who serves as the protagonist’s guardian. As a consequence, Teki is a favorite name for a beloved pet in Minkai and several other nations. Several other cultural ties to the Tayagama include the following.

* It is considered an ill omen to name one’s child after the protagonist of the Tayagama, Tayago, who in the end is killed by a vengeful oni. Tians often warn foolish children “not to follow in the path of Tayago.”
* A tree or bush with a green cloth tied to it found along a path indicates that a hidden source of drinkable water or a plant bearing edible fruit lies nearby. This is a reference to the Tayagama’s protagonist, who comes upon a magic green scarf that guides him to that which he seeks when he lets it blow in the breeze. (Of course, in real life, bandits sometimes use this custom to trick unsuspecting or superstitious travelers into ambushes.)
* An adult who claps after sneezing reveals that she is a very superstitious individual. In the Tayagama, Tayago occasionally sneezes, blowing poor Teki away so that he must summon him back for aid by clapping his hands. This gesture, common among younger children, is considered silly by most adults.

== Kami-Humanoid Relations

Humanoid communities in Tian Xia have many different types of relationships with kami, and these variations are often related to the way in which a community interacts with its surrounding environment. Settlements that depend on cooperation with nature, such as those of farmers and herders, tend to coexist peacefully with kami. Citizens of these cooperative settlements often construct roadside shrines to kami, where they provide offerings of incense, rice, wheat, milk, and so on. In these communities, nearby areas of wilderness are frequently honored by the people with celebrations and festivals intended to foster harmony with the neighboring kami. Most such festivals occur at the beginning of planting and harvest seasons. Cooperative communities frown on outsiders who do not show proper respect for the natural world or violate sacred areas, seeing this as a direct assault on the safety of their homes and the kami they live with.

Communities that sap the land via exploitation or extraction—such as through mining, fishing, or logging— tend to have tense relationships with neighboring kami. In these locales, shrines are often forbidding places, visited by designated representatives who bear offerings composed of materials that were taken from nature. For instance, those living near an iron mine may leave a dagger or bowl of arrowheads. Local ceremonies are geared toward appeasement of the spirits rather than thanking them, and dour festivals are intended only to avert kami’s capricious wrath. Outsiders who anger local kami are treated with hostility for bringing misfortune upon a community, and the communities often demand recompense.

Places with naturally adversarial relationships with their environments—most notably urban centers—have difficulty maintaining relationships with kami. These larger settlements often try to appease kami in little ways, such as by constructing parks within city limits to placate the spiritual beings. More often, however, such communities resort to violence against kami, whom they see as enemies of progress or their industrial efforts. These settlements often place emphasis on setting up barriers and protections against kami, characterizing them as backward-minded monsters bent on destruction. Of course, even communities that have hostile relations with kami of the forest, rivers, and hills may have better connections with the kami of inanimate objects, such as dosojins and zuishins. An urban scholar may have a playful and cooperative relationship with a book kami or the kami of a library, and a blacksmith might work closely with a furnace kami.
