= Ecology of the Kami

link:../../index.html[Home] » link:../index.html[Jade Regent 2020] » link:index.html[Story Journal]

Kami are spiritual beings created by the gods and tasked with maintaining the balance of the natural world. This maintenance comes in the form of protecting the various creatures and things on the Material Plane that are often unable to protect themselves. Each kami has a particular “ward” that it watches over, such as an inanimate object, a plant, a creature, or even a region. Intelligent beings (such as most humanoids) and objects that exist outside of the natural order (such as undead creatures and constructs) do not have kami. One can predict the strength of a particular kami by the nature of its ward: A rock or frog kami may be a relatively impotent thing, but a redwood kami, a blue whale kami, or the kami of a mountain often exercises massive power. The vast majority of kami are good or neutral in alignment. Those rare kami who fall to evil—usually after failing their ward in some way—generally have their physical forms revoked by the gods, and are condemned to become wandering spirits who either perish in their aimless voyages or are pushed to become hateful and vengeful oni.

A kami forms an extremely intimate bond with its ward, melding with the object or creature the majority of the time and manifesting a physical body when it must protect the thing or otherwise chooses. A kami prefers its spiritual form more often than not, and assumes a physical form only when necessary, such as when it must communicate with mortals or shield its ward. While this manifestation leaves a kami vulnerable to death like any other mortal creature, the kami is almost always willing to make this sacrifice in order to protect its ward.

Not everything in the world has a kami, as there aren’t yet enough kami to represent every individual object, plant, and animal; filling this gap, however, is their eventual goal, and kami fervently spread themselves across lands in hopes of pairing every creation with a kami spirit. This grand design began in Minkai, and in the past several thousand years the kami have proliferated across much of Tian Xia. It is unclear exactly which regions the kami hope to expand into next, though they can potentially exist in any environment, and the other continents—including those of the Inner Sea region—are clearly viable options.