= Way of the Ninja

link:../../index.html[Home] » link:../index.html[Jade Regent 2020] » link:index.html[Story Journal]

Heavily shrouded in mystery and legend, the ninja clan is portrayed in various lights throughout the many lands of Golarion—most of which depict these collectives of guileful individuals as collaborations of violent rogues and assassins. Nowhere, however, is the mythos of the ninja clan so prevalent as in the birthplace of its tale, the nation of Minkai. Whether scheming within the sewers beneath a booming metropolis or huddled in the foothills of distant mountains, ninja hold sway in the underbellies of even the most ostensibly lawful societies, typically operating in shadows and under the guise of unified structures with larger goals.

== Ninja Clans

Ninja operate in a wide variety of circumstances, and under an equally diverse array of banners and goals. While many regard ninja as strictly evil entities who deal only in shadows and deceptions, the truth is that ninja can do as much to aid a society as to damage it, and that most of the time a ninja’s motives are as elusive as the masked individual herself. Tales abound of vigilante ninja who assassinate corrupt dictators in the dead of night, yet more often ninja act as merciless mercenaries killing for the coin of powerful merchants and politicians. These masked individuals do not usually construct such elaborate schemes by themselves, however, and most subscribe to familial structures known as clans, which house members who share similar skills and motives. While ninja are commonly feared as glorified assassins, murder is merely a single facet of the shadow warriors’ array of expertise, and they just as often possess the skills of spies, scouts, and informants. Each clan specializes in certain aspects of the ninja arts, such as espionage, kidnapping, or burglary, and a clan’s particular realm of expertise is often a fair indicator of its larger-scale intentions and dealings.

The history of ninja clans in Minkai is almost as ancient as the nation itself, for the rogue organizations developed at the same time that Minkai warfare became a prominent driving force in the expansion of the empire, with small sects of shadowy warriors rising to power and functioning as soldiers of fortune for the wealthy warlords of the time. Clans’ presences within Minkai society grew further as feudalistic principalities gave way to more elaborate governing forces, and open warfare became less viable than covert political dealings. As the Minkaians became accustomed to peace and a sense of calm within their governments, the need for ninja clans continued to expand, taking the fights from the crowded battlefields to the secluded shadows. While the samurai of Minkai—and the rest of Tian Xia—continue the tradition of honorable battle, no such over-arching strictures necessarily restrain ninja, allowing these warriors of darkness to infiltrate and thrive in countless communities.
