= Into the North

link:../../index.html[Home] » link:../index.html[Jade Regent 2020] » link:index.html[Story Journal]

The route from Brinewall to Kalsgard passes through the Nolands and enters the Lands of the Linnorm Kings, where it joins an existing trade route between the dwarven mine at Kopparberget and the city of Jol before continuing north into the Grungir Forest. The caravan road crosses the eastern neck of the Grungir until it reaches the bridge to Losthome, at which point the route follows the western bank of the Thundering River as it meanders north, connecting the many small settlements and steadings that stand upon the river’s banks. At the confluence of the Thundering and Rimeflow rivers, the trade route branches again, with one trail crossing the Skalsbridge and heading northeast toward Trollheim while the other continues along the Rimeflow to Kalsgard. The total distance from Brinewall to Kalsgard is about 440 miles; the time it takes to travel between them is around 2 weeks. The trip is largely uneventful save for the occasional glimpse of some of the larger predators of the region, such as bears and mountain lions shadowing the caravan for a mile or so before losing interest and searching elsewhere for easier prey. The ravens and sea birds of the region are plentiful overhead, and the caravan’s travelers can even supplement their provisions with an elk or two taken down in the hills and at the forest’s edge.

== The Watcher

During the journey, the heroes notice that one of the ubiquitous ravens shadowing the caravan in the hope of finding scraps to eat is a much larger specimen than normal, perhaps the size of a small dog. Once this particular raven has been spotted, the heroes can easily pick it out from the rest and recognize that it returns every couple of days before departing again. Additionally, the heroes notice that one of its wing pinions is blood-red in color. Such a "`blood-feather`" raven is seen as an evil omen and is often thought to be in the service of dark powers. The raven remains out of range of missile weapons and spells, usually just perching on a tree branch and watching or soaring high above. Once Losthome comes into sight, the raven no longer appears.

== The Fury of the Northmen

The caravan camps for the night at Skalsbridge, an ancient bridge that crosses the Thundering River where it joins with the Rimeflow. The night is cold, and a frozen mist clings low to the ground, making the light dim, even within the range of the campfire light. The heroes spot the blood-feather raven perched atop one of the lintel posts of the bridge above the campsite. When spotted, it quickly flies away into the concealing darkness. Additionally, the heroes hear the sound of a muffled oar in an oarlock out on the darkened river.

The sounds of night are muted amid the freezing fog that clings to blankets, cloaks, and Varisian mustachios alike. The dull silence is suddenly broken by the scrape of wood upon the gravel bank of the river—a boat has beached just beneath the bridge—quickly followed by the splash of feet in the shallows and the oath-cries and battle-songs of Ulfen raiders!

A group of 40 unruly Ulfen warriors charge into the camp spreading out to attack the caravan in the fog and darkness. The heroes quickly defeat two-thirds of the raiders, and the survivors flee into the night hoping to escape into the wilderness. A search of the raiders’ bodies, however, reveals that each wears a gold arm-ring—a common Ulfen armband worn around the upper arm—bearing a stylized depiction of a lion’s head embossed in the metal. The heroes also find their boat, a small river knarr with a length of 52 feet and 20 sets of oars (equivalent to a keelboat but with the speed of a longship). Painted upon its prow in Skald is the name _Aril’s Hammer_. There is nothing of interest aboard the ship.

== Kalsgard

Upon arrival in Kalsgard, the heroes’ caravan immediately moves into the city’s Bone Quarter to camp among the others of its kind in order to avoid further attention. Sandru Vhiski suggests that the heroes procure their own quarters within the hustle and bustle of the city to further throw off suspicion while the caravan surreptitiously makes preparations for the journey over the Crown of the World to Minkai. Sandru also tells them they need a guide who can take the caravan safely across the Crown of the World to Minkai.

== In Search of Suishen

From the visions and knowledge imparted to them by the Amatatsu Seal at the end of the previous adventure, the heroes know that Ameiko’s grandfather, Rokuro Kaijitsu, sold the sword Suishen to a merchant and collector in Kalsgard named Fynn Snaevald. Even though the sale took place almost 60 years ago, it is still the best lead the heroes have to help them find the sword. The heroes learn that Fynn Snaevald is still alive and well, working as an independent trader of amber and whale oil, and a well-known collector of Tian antiquities. His home in Kalsgard’s Amber Quarter can easily be located.

Simply knocking at the sturdy door of Snaevald’s home brings an answer from the old merchant himself. Mention of Tian Xia'n sword gains the heroes an audience. *Fynn Snaevald* is slender and wiry, with blue veins crawling across his arms and neck beneath a shock of white beard and hair that floats around his head like a halo. Although well into his nineties, Snaevald is still hale, hearty, and feisty. He is happy to talk to the heroes about Tian Xia and reminisce about his long-ago purchase of the Tian sword over mugs of warm ale and crusty bread brought from his kitchens by well-groomed servants.

Fynn is particularly animated in talking about the sword, and relates that only a few weeks ago (shortly after the heroes discovered the Amatatsu Seal in Brinewall, in fact) a band of masked, black-suited thieves broke in and stole the sword. Fynn was not at home at the time, but he says that several of his servants were killed in the robbery and that the only thing taken was the sword, which he kept on display above his hearth. One of his servants was still alive when he arrived home, and was able to tell him what had occurred before dying. The only description the servant could give was that one of the masked intruders was much taller than the others and seemed to be in charge. Fynn reported the robbery to the city’s watchmen, but nothing ever came of it.

Since the heroes expressed interest in the sword, Fynn makes them an offer. He Fynn Snaevald states that other than as a trophy that collected dust for 5 decades, he never cared much for the sword. Although he tried to carry and wield the weapon in his younger days, every time he did so it gave him an uncomfortable feeling. At this point, Fynn doesn’t really care about getting the sword back. He is old, and has no heirs to leave it to when he dies. However, the sword was his property, and that, along with the deaths of his servants, makes him an aggrieved party in the matter. Under the laws and traditions of the Ulfen people, Fynn is entitled to weregild—compensation for the stolen item from the perpetrator. But since no weregild has been offered, he is entitled to pursue blood vengeance against those who have wronged him. Fynn states that he is now an old man and incapable of pursuing that blood vengeance on his own, but it is within his rights to appoint proxies to do so on his behalf. Therefore, Fynn has a proposition for the heroes. If they can discover who perpetrated this crime against him, exact blood vengeance against them to defend his honor and property rights, and recover the sword, he will reward the heroes by giving them the sword as a prize.

When the heroes bring up the matter of the lion’s head arm-rings. Fynn explains that, armrings are common adornments among the Ulfen, but the lion’s head emblem is unique enough that Fynn recognizes its source. A local ring-giver (a term used for a minor chieftain or landowner who maintains a standing body of followers) named Asvig Longthews is known to have a stylized lion’s head in his personal runes. The discussion jogs Fynn’s memory, and he recalls that his dying servant mumbled something about "`paying the lion’s due`" with his last breath. With no context or reason to suspect Asvig, Fynn made nothing of it and assumed the dying man had lost his wits. However, the servant could have been telling Fynn that he would need to seek blood vengeance from Asvig Longthews. Fynn adds that Asvig’s nickname "`Longthews`" refers to the fact that the man is known to be extremely tall, like the man who led the robbery—another connection that hadn’t occurred to him before. Fynn does not know where Asvig’s farm is located, only that it is outside of town and that Asvig is known to have several dozen warriors and retainers, any number of whom could be present there at any given time. Asking around about the location of Asvig Longthews’s farm, provides it's location.
