= Primary NPCs

link:../../index.html[Home] » link:../index.html[Jade Regent 2020] » link:index.html[Story Journal]

== Kaijitsu Family

The Kaijitsu family is known for their artistry and skill at glassblowing, are part of the Varisian aristocracy of merchant nobles, and are one of the four founding families of Sandpoint. They previously resided in the city of Magnimar (west of Sandpoint along the coast). Atsuii Kaijitsu, mother of Ameiko, Tsuto, Kuro and Shiro Kaijitsu, died in a fall from the cliffs near her house, 9 years ago, in 4702 AR. In addition to the legitimate heirs of Ameiko, Kuro and Shiro, the Kaijitsu's also have an estranged half-sister Amaya, in Westcrown, born from Lonjiko’s scandalous affair with a Chelish noblewoman in 4680.

== Ameiko Kaijitsu

Although she’s technically the head of one of Sandpoint’s noble families, Ameiko Kaijitsu is more at home running things at her tavern, the Rusty Dragon, than she is among the small town’s aristocracy.

Female human aristocrat 1/bard 3/rogue (rake) 1 +
CG Medium humanoid (human) +
*TACTICS* +
*Before Combat* Ameiko casts unseen servant every morning. +
*During Combat* When able to strike first in a combat, Ameiko uses bravado’s blade to intimidate foes instead of dealing sneak attack damage. Ameiko begins combat by activating her bardic performance. She always uses Arcane Strike in battle (these bonuses are included in her stats above). +
*Morale* Ameiko is loyal to her friends, and never abandons an ally in combat. Alone, her bravery isn’t as great. When she is faced with a dangerous foe and has no allies in peril, she prefers to flee if reduced below 15 hit points. +
*Feats* Arcane Strike, Dodge, Iron Will, Weapon Finesse +
*Skills* Acrobatics +10, Bluff +12, Diplomacy +12, Intimidate +12, Knowledge (arcana) +6, Knowledge (local) +8, Knowledge (nobility) +6, Knowledge (religion) +6, Perception +7, Perform (sing) +12, Perform (string) +12 (+14 with mwk samisen), Profession (tavern keeper) +4, Spellcraft +9, Stealth +10 +
*Languages* Common, Tien, Varisian +
*Combat Gear* potion of remove disease, wand of cure moderate wounds (25 charges), wand of identify (40 charges); *Other Gear* +1 leather armor, +1 mithral rapier, daggers (3), ring of protection +1, belt pouch, gold signet ring worth 100 gp, masterwork samisen, silver holy symbol of Shelyn, spell component pouch

Ameiko is a beautiful but somewhat irreverent woman of Tian descent who runs Sandpoint’s Rusty Dragon tavern and happens to be a member of one of Sandpoint’s founding families. Her parents and older siblings have met unfortunate ends over the past several years, leaving the young woman as the sole remaining Kaijitsu in town. Ameiko may be among the town’s nobility, but she’s never really cared for the aristocracy—she’s always had an urge to explore, and loves hearing stories of adventures and daring deeds. While she has a lot of friends and admirers in town, Ameiko has never accepted anyone as anything more than a friend, diplomatically avoiding personal questions and proposals of romance, much to the frustration of several eager suitors in Sandpoint. She’s a talented singer and samisen player, and if she wanted, Ameiko could probably lead a comfortable life in Sandpoint, but she’s growing increasingly bored and impatient with having a "`safe life`" in a "`safe town.`" If the chance to go on a grand adventure presents itself, she’d sell the Rusty Dragon in a heartbeat to seek her fortune.

Ameiko was born in 4689 AR to Lonjiku and Atsuii Kaijitsu. Although she’s not Atsuii’s or Lonjiku’s first child, she was the first legitimate child from that marriage. Ameiko had a lonely childhood. Her father strictly controlled who she could keep as friends, and filled her days with lessons in music, diplomacy, magic, and academic subjects. He kept a close eye on her, but Ameiko still managed to sneak into town to play with friends, explore old buildings, and visit her half-elven half-brother Tsuto at Sandpoint’s Turandarok Academy every chance she could.

When she was 13, Ameiko tried to reconcile the bad blood between her brother Tsuto and father, but the attempt backfired. Tsuto struck her in a fit of rage, and Ameiko was so betrayed and distraught by this that she ran away from home to Magnimar for several months. When she learned of her mother’s death in a fall from the cliffs near her house, though, Ameiko returned home to Sandpoint. She found life at home more unpleasant than ever, but when another family argument broke out at her mother’s funeral and Tsuto left town, Ameiko resigned herself to staying in Sandpoint to care for her father and younger siblings Kuro and Shiro.

Ameiko left home for the second time at age 16, joined an adventuring group, and became particularly good friends with the group’s priest of Shelyn, a handsome young Varisian man named Alder Vhiski. But in 4706, the group was captured by a degenerate family of backwoods cannibals living in an old mine in the southern Fogscar Mountains. The group was within a hair’s breadth of being eaten, abused, and worse by the degenerates, but Alder led a heroic attempt to escape. The resulting flight from the mine was nightmarish, as members of the group were picked off one by one by the pursuing cannibals, who were led by a spry druid who favored snakes as his pets. As the group neared the exit, only Ameiko, Alder, and Alder’s brother Sandru remained alive, but as they prepared to scramble into a rickety rowboat that would take them to safety, Ameiko was attacked by the druid’s animal companion, a viper of prodigious size. Bitten twice, Ameiko would have died had Alder not pulled her to safety, and in so doing Alder was himself bitten. Already weakened from the fight, the snake’s venom killed him. The last Ameiko saw of Alder, he was being torn apart by the degenerates. With Sandru’s help, the two survivors eventually made it back to Sandpoint, but they never spoke of what they had endured in that old mine. Some months later, Ameiko got a tattoo of a snake on her left arm and shoulder as a sort of memorial to Alder, then cashed in most of her earnings from her adventures and purchased an old tavern in downtown Sandpoint called the Rusty Dragon. Since then, she’s run the Rusty Dragon as a place for adventurers to gather and relax.

The last few years have been hard on the Kaijitsu family, with the death of both father Lonjiku and half-brother Tsuto during a series of violent goblin attacks on Sandpoint. While Ameiko now runs both the Rusty Dragon and the Sandpoint Glassworks, and she still has pride in what she’s accomplished in town, her hopes to leave Sandpoint and its bitter memories behind for a grand new adventure grow with each day.

== Koya Mvashti

While most people might think Koya’s lived a full life, she aches to make one grand journey worthy of being retold as a legend before she grows too old to travel.

Female old human cleric of Desna 4 +
CG Medium humanoid (human) +
*TACTICS* +
*During Combat* Koya avoids combat if possible, preferring instead to cast sanctuary and then move among the battlefield casting healing magic on her allies. If faced with a situation where she can’t avoid healing enemies with her channel energy ability, Koya always chooses to use the ability anyway if an ally is wounded and she has no other options. If confronted on her own, she uses sanctuary to aid in her escape after casting longstrider to increase her speed. +
*Morale* Koya flees from any combat where she has no allies, but if even one ally remains alive, she remains to try to keep him alive as long as she can. +
*Feats* Brew Potion, Extra Channel, Fortune Teller* +
*Skills* Heal +11, Knowledge (religion) +8, Profession (fortuneteller) +11, Sense Motive +11, Spellcraft +8 +
*Languages* Common, Varisian +
*Combat Gear* scrolls of cure moderate wounds (5), scroll of remove curse, scroll of remove disease, wand of cure light wounds (28 charges); *Other Gear* +1 leather armor, masterwork starknives (2), ring of protection +1, amethyst ring worth 100 gp, harrow deck, silver holy symbol of Desna, silver necklace worth 30 gp

Until she passed away from natural causes just a few months ago, Madame Niska Mvashti was the oldest person in Sandpoint. No one quite knows exactly how old the Varisian seer actually was when she died (she was already old when Sandpoint was founded over 40 years ago)—but the fact that her only daughter Koya is herself an old woman is a telling fact. Koya has spent a fair amount of her life traveling Varisia with a number of caravans, serving as a healer when she was younger and more recently as a fortune-teller. For the past several years, she’s in the company of her adopted son Sandru Vhiski as they travel on a regular caravan route between Riddleport, Magnimar, and Korvosa two or three times a year. Their caravan spends most of its time relatively close to Sandpoint, though, and that has suited Koya fine, since it gave her more time to care for her aged mother.

Now that old Niska has finally died, though, Koya’s mourning has transitioned into a sort of morose melancholy. A life-long worshiper of Desna, she’s come to realize that while she’s traveled extensively throughout the Varisian lowlands, she’s never been beyond the region’s borders. Tales of other Desnan explorers have long delighted Koya’s sense of wonder—even her own mother reputedly took part in several extensive caravans that traveled as far as the Lands of the Linnorm Kings and even down to Qadira. Koya’s having something of a latelife crisis as a result—a growing sense of disappointment that she’s never made a long caravan trek. With her mother dead, Koya has little reason to stay in Varisia, and she’s been pressuring Sandru to take a long journey soon: "`The sooner the better, cause I won’t be around for long!`" Koya’s in remarkably good shape, physically, for a woman well over 60 years in age—obviously, longevity runs in her family—but with each year that passes, the chance of her getting to experience a truly epic journey like the ones in her favorite stories grows narrower.

Koya has wanted to travel to the far corners of Golarion since she was a child and first saw a map of the world in an old history book she came across while sneaking through her mother’s impressive collection of notes, trophies, and keepsakes from her extensive travels. Although Koya has since come to learn that the old map was rather inaccurate, she’s never lost the sense of wonder she gained from the simple notion that the world she’d thought she’d known was so much larger than she’d ever imagined. Likewise, a childhood trip to Korvosa impressed upon her how different the world can be as you travel from plains to forests to swamps to mountains to large urban centers. The idea that one could make journeys 10 or even 100 times as long as the caravan route running from Sandpoint to Korvosa has long been a point of fascination and wonder for Koya.

But Koya never went on that long journey. She always assumed there would be the chance for an adventure in the near future, but the present always seemed to have a knack for getting in the way. Responsibilities to her family caravan, her several tempestuous love affairs as a young woman, the task of caring for unfortunate children who had no mother of their own (most notably Sandru Vhiski, and perhaps one of the PCs if the character selected the correct Campaign Trait from the Jade Regent Player’s Guide), and most recently caring for her elderly, but not quite completely infirm, mother all worked to keep her at home. Just as one phase of her life seemed ready to close, the next began, and before she knew it, the unwelcome kiss of old age had crept into her aching bones and wrinkled face.

With her mother now dead, Koya is eager to seize what she thinks might be her last chance for that great, world-spanning journey. Lately she’s been traveling with her adopted son Sandru in his caravan, serving as a fortuneteller, and she hopes that her frequent attempts to convince him to make a long journey will bear fruit soon. Koya longs to travel beyond the borders of Varisia, whether south to Cheliax and beyond or north to the Lands of the Linnorm Kings and the Crown of the World. Koya would love to visit another continent as well, if the opportunity presented itself, so she could leave her own "`found-mark`" in distant lands.

Koya serves as the spiritual core of the caravan. As the most likely candidate for the caravan’s fortune-teller job, she serves as an advisor for most of the travelers in the caravan, and Koya’s stories, fortune-telling, and sense of humor should be a staple of all nights spent on the road. The longer the journey progresses and the more miles the caravan piles on, the more energetic and excited Koya seems to become, almost as if the journey is invigorating her rather than exhausting her, as one might expect from such a long journey.

== Sandru Vhiski

Sandru Vhiski never took the easy path in life—mostly because life’s easiest path could have been to follow his brother into a life of crime among the Sczarni, a path Sandru prides himself for having never set a single foot upon.

Male human rogue (swashbuckler) 4 +
NG Medium humanoid (human) +
*TACTICS* +
*During Combat* Sandru stays mobile in combat, using Acrobatics to avoid attacks of opportunity as he flanks foes and to prevent enemies from taking full-attack actions on him. He uses Power Attack in all fights, but does so with a relatively unique style that makes him seem more graceful than brutal in nature. +
*Morale* Sandru is stubbornly brave and has a hard time envisioning his own demise. As a result of this attitude, he fights to the death. +
*Feats* Improved Initiative, Iron Will, Power Attack, Toughness, Weapon Focus (scimitar) +
*Skills* Acrobatics +9, Appraise +7, Bluff +8, Craft (carpentry) +7, Diplomacy +8, Disable Device +8, Handle Animal +5, Knowledge (history) +4, Perception +7, Profession (merchant) +7 +
*Languages* Common, Varisian +
*Combat Gear* potions of cure light wounds (3), potion of cure moderate wounds; *Other Gear* +1 chain shirt, +1 buckler, +1 scimitar, mwk shortbow with 20 arrows, belt pouch, bottle of fine brandy worth 50 gp (4), everburning torch, masterwork thieves’ tools, trail rations (4 days), wineskin

Only a few years from middle age, Sandru Vhiski is a charming man, handsome and irreverent in precisely the ways that could have made him a highly successful Sczarni con artist, even before one takes into account in the fact that his older brother, Jubrayl, is Sandpoint’s local Sczarni leader. Sandru doesn’t live in Sandpoint, although he considers himself one of the town’s citizens nevertheless. He’s only in town a few days out of every month, for his caravan is one of the region’s busier examples. Traveling with his adopted mother Koya Mvashti and a pair of Varisian brothers named Bevelek and Vankor Dalmuvian, Sandru makes the trip from Riddleport to Magnimar to Korvosa several times a year. While he makes enough money on these journeys from trade, money isn’t Sandru’s primary motivation—he loves the road, and he loves the tradition. It doesn’t take much to get Sandru talking about Varisian history, dance traditions, scarves, fortune-telling, horses and wagons, landmarks and legends. In the off-seasons, when weather makes travel too dangerous or too uncomfortable, Sandru prefers to stay in Magnimar, where he helps other Varisians with his carpentry skills and flirts with the political scene in that town. He’s not yet had the conviction to fully become a representative of his people in Magnimar, though, since he knows the call of the road will pull him from any local responsibilities as soon as the rains clear each spring.

The Vhiski family has been involved with the Sczarni for as many generations as anyone cares to look back upon. Not every Vhiski throws in with the gang, but enough do that when one comes along who has no interest in the Sczarni life, it’s difficult for him to prove his disinterest in crime to outsiders. Sandru’s early childhood schools were back alleys and waterfront taverns, and training in the art of the con, dirty fighting, sabotage, and picking locks replaced lessons in numbers, arts, and literature. From an early age, though, Sandru’s sense of fairness and compassion hampered his advancement in the ranks of the Sczarni, and the mockery and derision his hesitance earned him only strengthened his convictions.

When a violent storm struck the Varisian coast in 4687 AR, Sandru’s parents were among those slain by the floods and winds that tore the Lost Coast apart. Sandru and his brothers Alder and Jubrayl emerged from that catastrophic event as orphans. Yet while tragic, this event was ironically just the thing to save Sandru from a life of crime. While Jubrayl was old enough at that point to strike out on his own (and thus fell in completely with the family’s criminal traditions), Sandru was still a young child of 7 and his younger brother Alder barely 2. His care fell to Koya Mvashti, a family friend and practically an aunt to the young Sandru. Under her guidance and support, Sandru managed to avoid falling in with the Sczarni, and when he grew of age, he sought employment as a caravan guard.

For several years, Sandru avoided Sandpoint, but after he lost his job, he joined up with a group of adventurers eager to explore western Varisia. As fate would have it, Ameiko Kaijitsu was also in the group. Sandru and Ameiko hit it off at once and became close friends. Indeed, Sandru was quite taken with the lovely young woman, but their age difference (he was 26, while she was only 17) and Sandru’s sense of honor kept him from pursuing a romantic relationship with her. Instead, he watched enviously (yet graciously) as Ameiko and his younger brother Alder began to fall in love.

The trio’s brief adventuring career was quite successful, but as recounted in Ameiko’s history, ended in tragedy. For many years after Alder rescued Ameiko and lost his life to the cannibals, Sandru couldn’t stand to be around the young Tian—she reminded him of lost opportunities and lost family. So while Ameiko invested her adventuring spoils in Sandpoint, Sandru invested his in the road, throwing himself into a much more honorable Varisian occupation, that of caravan owner. For the next several years, Sandru’s life was the road. He’s since mostly recovered from the bad times, and now visits Sandpoint and Ameiko often. He thinks of her now as a younger sister, and often worries that her capricious and often rebellious nature will someday force her to choose between the life she wants and the life she’s inherited as one of Sandpoint’s nobles.

Sandru is the owner and primary driver of the caravan destined to take the PCs over the Crown of the World and into Minkai. Just as he plays the role of surrogate older brother to Ameiko, he should start to fill that role for most, if not all, of the PCs. Sandru’s led a relatively lonely life, though, and most of those who have shown romantic interest in him have been associated with the Sczarni, while those to whom he is attracted tend to see him either as a brother or are already in relationships. While Sandru knows he could woo a paramour away from his or her lover if he put his mind and his charms to the task, he also knows he could never stay long with a lover who wasn’t faithful or devoted enough to stick with whoever came before him. Caught in this complex tangle of emotions and honor, Sandru has started to think of himself as a life-long bachelor, and with each passing year consigns himself to the growing certainty that he’ll remain alone until his final days. As a result, while he’s a friendly and personable character, he tends to miss such social cues or avoid romantic approaches entirely.

== Shalelu Andosana

Shalelu is older than the town of Sandpoint, yet she’s come to think of it as her hometown—a town that has finally grown up enough to survive on its own without her watching over it from the wild.

[%hardbreaks]
Female elf fighter 2/ranger 4
CG Medium humanoid (elf)
*TACTICS*
*During Combat* Shalelu prefers to fight with her bow, resorting to melee only when truly desperate or when an ally seems in dire need of healing from her wand.
*Morale* Shalelu is loyal to her friends, and as long as even one of them remains in danger she won’t abandon them. That said, if she feels she can escape, get help, and return in time to save anyone captured by enemies before it’s too late, she might try to do so.
*Feats* Dodge, Endurance, Point-Blank Shot, Precise Shot, Rapid Shot, Skill Focus (Acrobatics), Weapon Focus (composite longbow)
*Skills* Acrobatics +12, Knowledge (nature) +8, Perception +12, Stealth +15, Survival +10, Swim +10
*Languages* Common, Elven, Goblin
*Combat Gear* sleep arrows (10), potion of delay poison, potions of lesser restoration (2), wand of cure light wounds (25 charges), antitoxin (2); *Other Gear* +1 studded leather, +1 composite longbow with 20 arrows, masterwork short sword, amulet of natural armor +1, campfire bead*, cloak of resistance +1, backpack, bedroll, climber’s kit, flint and steel, manacles, silk rope (50 ft.), sunrods (3), trail rations (4 days), waterskin, winter blanket, wooden holy symbol of Desna

Although Shalelu Andosana is something of a mystery in Sandpoint, she’s certainly one of the town’s most admired defenders. Like Sandru Vhiski, she doesn’t actually live in town, but she sometimes spends the night at the Rusty Dragon free of charge, thanks to her friendship with Ameiko Kaijitsu. Everyone in town knows that Shalelu is something of a loner and prefers to spend her time wandering and exploring the wilderness around Sandpoint. She periodically vanishes from the region for weeks or even months at a time to visit friends elsewhere in Varisia, but she never fails to return to Sandpoint. No one quite understands why she keeps coming back. When asked why, she merely says, "`Someone’s got to keep an eye on you all.`" Her reports of goblin activity have helped save folk from ambushes or warned the militia of possible attacks on the town or its farmlands numerous times. Yet in recent days, Sheriff Hemlock has taken a more active role in watching over the surrounding land. His militia is better trained than ever before, and Shalelu’s aid in keeping an eye on the hinterlands is growing less and less necessary. She actually seems relatively pleased with this, as if she’s proud that Sandpoint is finally starting to look after itself. She’s even hinted that she’s thinking of taking a long journey away from town sometime in the future, but when pressed for details, she just shrugs and changes the topic.

Shalelu is still relatively young at 130 years of age, but she can remember when the Lost Coast was truly lost, when only goblin lairs and Thassilonian ruins could be found along its length. Yet for much of her life, Shalelu’s visits to southern Varisia were not nearly as common. Born and raised in the small village of Crying Leaf, Shalelu is an only child whose father was slain not long after she was born by a particularly brutal bugbear assassin, exposing Shalelu to far more goblinoid cruelty than most elves her age dream of in their worst nightmares.

It took Shalelu’s mother Seanthia nearly a hundred years to find a new love, and when she did, she chose a human mercenary, scandalizing much of Crying Leaf. As shocking as the choice may have been, Shalelu saw how happy this man Jakardos made her mother, and she loved him as a father for that kindness. But when her mother died in a fight a green dragon a few years later, Jakardos left without saying goodbye, shattering Shalelu’s opinion of him. The loss of her mother and stepfather sent Shalelu into a terrible depression, and she left Crying Leaf to seek out a new home.

Shalelu came to Sandpoint, where she found a burgeoning human village that was growing rapidly into a town, but that was plagued by goblins. Shalelu took Sandpoint under her wing, and for many years she protected it from goblins, bugbears, ghouls, and worse. Recently, Shalelu sought out Jakardos at his new home in central Varisia, and her reconciliation with her aging stepfather finally helped her come to terms with the violent attack that killed her mother. And when Shalelu returned to Crying Leaf to aid in dealing with the drow problem in the nearby Mierani Forest, she was able to help kill the same green dragon responsible for her mother’s death.

Shalelu is now in one of the happiest times of her life, and has been seized with a restless wanderlust. In recent years, Shalelu has built a strong friendship with Ameiko Kaijitsu as well, and sees her as a younger sister. Shalelu knows that Ameiko is haunted by tragedies, and in some ways sees a reflection of her own sad history in Ameiko. Shalelu hopes to find some way soon of helping her friend overcome her melancholia—perhaps a nice long trip will fit the bill.
