= Ordu-Aganhei

link:../../index.html[Home] » link:../index.html[Jade Regent 2020] » link:index.html[Story Journal]

== Living Legendry

In many of the nations and regions that collectively make up the land of Tian Xia, histories stretch back to points so ancient that the distinction between fact and myth blurs. From the legendary past rise monuments depicting fantastic heroes and strange beings, personages none now living can prove ever truly existed—yet who are believed in all the same. In some places, these figures are merely legends and fairy tales told to children. In others, evidence of wondrous deeds remains. And in still others, these ancient beings yet watch over their people, guarding those with the faith to see past the veils of time.

== Deserving of Honor

Not all the creatures spoken of in the tales of Minkai are as ferocious as the dreaded oni or as protective as the mysterious kami. Some exist merely to exist, taking delight in life and all the pleasures the world has to offer while simultaneously accepting it as it is. Among these are the raccoonlike tanuki, jolly and clever creatures equally as likely to wander the world in search of new experiences as they are to make someplace their home and enjoy its comforts. Yet many stories warn listeners to honor even such whimsical creatures, as their powers make them more than mortals, and those who rouse their ire suffer terrible fates.

== The Five Feasts of Hongal

The heroes arive in Ordu-Aganhei, the capital of the nation of Hongal and the northernmost city in Tian Xia. It lies on the edge of the Arctic Circle and is the primary trade hub on the Tian side of the Path of Aganhei. Ordu-Aganhei is crammed between stout timber walls 40 feet high, topped with spikes replete with the severed heads of bandits who preyed upon the Path of Aganhei. They enter the city through its north gate, a decorated tower with a single 30-foot-high reinforced iron door and some 30 guards inside. The gate guards examined the travellers with barely hidden suspicion. The guards’ examination is strict and thorough, dust swirling around them as they work. Just as it looks like the guards won’t allow the heroes into the city, however, a well-dressed man appears at the gate from within the city, prostrates himself (quite literally) before them, and makes a speech.

Honored guests! Welcome, welcome, and three welcomes more! Please ignore these slithering worms beneath your feet—I assure you they shall be punished for their insolence. Prince Batsaikhar, golden orb of sunlight at the black portal of barbarism, bids you welcome to Ordu-Aganhei, the City at the Edge of the World. My most munificent lord invites his honored guests to his humble palace to rest, dine, partake in polite conversation, and perhaps indulge in some pleasure. The Golden One says he hopes you will honor him with your clever speech from strange lands, a speech that he of all men in Hongal has mastered. He is eager to hear of your journey across the Crown of the World in this most difficult time of travel.

To Ameiko, Koya, Shalelu and Shiro he offers a special gift—a black rose—and these words: “There is no fire like the fire in the souls of the women of far lands. Beauty is the wisdom of women, and wisdom is the beauty of men.” Accepting the invitation the heroes are guided through the streets of Ordu-Aganhei to the enormous wooden Palace of the Prince. The city’s layout is confusing, with narrow, winding streets. Buildings are timber framed and have high, gabled roofs and ornate, decorated eaves. A large, parklike garden surrounds Ordu-Aganhei’s central lake, which lies more or less in the middle of the city. The park is flanked on one side by the Palace of the Prince, guarded by hundreds of soldiers, and on the other by the temple of Abadar, known in Tian Xia as the God of Walls and Ditches. The streets are immaculately clean. Prayer flags of all colors dance in the wind from every gable and roof. Everywhere one turns a shop is selling something, and the heady scent of incense mingles with the smell of unfamiliar cooked foods.

The heroes are taken first to gender separate steaming lakes to bathe, while bathing some of the endless assistants take their clothes for washing leaving behind fresh and beautiful garments for you to wear to meet the Prince. After bathing and dressing the heroes are hurried past countless guards and groveling slaves to the palace’s central courtyard, a vast chamber nearly 100 yards across built around a steaming lake. Orchids grow in gardens overlooking the lake, while colorful herons swoop through the air, all beneath a ceiling hidden by prayer flags. On a huge bed surrounded by colorful silks, painted screens, and beautiful white-painted women sits an enormous, smiling man barely dressed in voluminous robes—Prince Batsaikhar. Immediately behind him stands his bodyguard, a tall figure in full samurai armor, carrying an enormous drawn sword.

When the heroes are brought into his presence, the prince is almost unbearably polite, plying them with extravagant food and drink. He is anxious to hear about their travels and their reasons for crossing the Crown of the World at this time of the year. Batsaikhar announces that the travellers shall be afforded the status of royal guests. He instructs his staff to provide them the best rooms and begin preparations for the Five Feasts of Hongal in their honor. The first feast will take place that very night; the last will take place in 5 days’ time across the whole city. The prince then dismisses the heroes. The Palace of the Prince is a large and rambling structure, and as guests, they have free rein. However, there are so many guards, retainers, and advisors in the palace that guests are hard pressed to do anything without at least half a dozen people appearing around them to help. The guest rooms are luxurious, with goose feather beds, warm fireplaces, access to steaming lakes to bathe in, and endless assistants to pamper guests. Guests may also visit the city at their leisure, though the prince will assign several guards and servants to accompany and guide them through the city.

The heroes spend most of the first day making arrangements to replace the caravan that was lost, acquiring new wagons and horses, and browsing the cities many shops. The Feast of Three takes place on the first night in Ordu-Aganhei as guests of Prince Batsaikhar. The feast as with all his feasts is a lavish affair, and take place in the prince’s throne room courtyard with over 300 guests, including Batsaikhar’s wives, courtiers, concubines, subjects, and slaves, who all react in exactly the same way that he does. There are many strange foods available at the feast and the heroes are asked to compete against the prince’s royal guards in an exhibition of the Three Games of Hongal: mounted archery, bareback horse racing, and wrestling. While the heroes do poorly in the first two challenges, they win at wrestling saving face.

On the second day the heroes notice the prince frequently summons Shalelu to speak with her. The Feast of the Ancients takes place on the second night and once again there are many strage foods available, all new and different from those that came before. After entertaining the guests with shadow puppet theater, singing and music, the heroes are challenged to likewise entertain the guests. Unfortuneatley the heroes fail to impress on all counts, however the prince continues smiling and politely ignores the failure, as criticizing guests would be the height of rudeness.

On the third night, the Feast of the Honored Visitors is held. For this feast, the guests must advise the royal chefs what to cook, and must provide the entertainment for the feast. The prince’s advisor Chua wakes the heroes at dawn and asks for instructions for the feast—the royal household is ready to act under their direction. The heroes have to feed and entertain the prince’s 300 guests, however the prince’s chefs are totally unfamiliar with
Avistani cuisine. The heroes rally together and manage to pull off an impressive affair, satisfying the prince and his guests.

== An Unexpected Ally

By the fourth day it has become apparent that the prince is fixated on Shalelu. During their stay, the prince has frequently summoned Shalelu. Batsaikhar makes no secret of his wonder and desire regarding Shalelu, but the prince is never threatening or aggressive. However his desire is open and plain as is that Prince is used to getting what he wants. Concerned for their friend the heroes restock their supplies preparing to depart, but before they can leave, a group of six Five Storms ninja attack the heroes in the market. The heroes gain an unexpected ally in their battle against the ninja, as a woman runs out of the crowd and begins attacking the ninja as well. After the battle, Kyomi introduces herself to the heroes. She is an ally of the kami of the Forest of Spirits and has walked a long way to meet them and offer Ameiko and her companions safe passage through the forest. She wispers that the kami are aware of the heroes’ arrival in Tian Xia and the precious treasures they bear with them—the Amatatsu Seal and a true Amatatsu scion. The ancient nature spirits are anxious to see the Five Storms destroyed and the rightful empress return to the throne of Minkai, but the kami are bound by ancient agreements not to directly interfere with the world of mortals, and so they have sent Kyomi as their herald and ambassador.

Kyomi informs the heroes that the Five Storms control much of Minkai, as well as the Spirit Road from Hongal to Minkai. If they wish to enter Minkai secretly, they need a less obvious way to enter the empire than the main road. Kyomi offers to guide them through the Forest of Spirits, the vast “haunted” forest that grows between Hongal and Minkai, via a secret route that bypasses the heavily patrolled Spirit Road. Once there, she promises to introduce the heroes to these mysterious allies and bring them to a place that may aid them all in the battle to come. She is as anxious to leave as the heroes and so they depart as soon as the caravan is ready, sending their oppologies and goodbyes to the prince via messenger. Before they can depart however, the prince delivers a gift of 5 tooled, gold-filigreed riding saddles worth 200 gp each. Each saddle also comes with a famed Hongali horse—a combat-trained light horse (with the advanced simple template)—worth 300 gp.
