= Assault on Ravenscraeg

link:../../index.html[Home] » link:../index.html[Jade Regent 2020] » link:index.html[Story Journal]

Once the heroes learn of Thorborg Silverskorr’s interest in Ravenscraeg (and the possibility that both _Suishen_ and Ulf Gormundr might be there), they have little trouble finding out more about it. Ravenscraeg was the hall of the Mad Reaver Snorri StoneEye. It is called Ravenscraeg because it lies high among the rocky crags south of Kalsgard, accessible only to the eponymous ravens that roost atop its ridgepole, save for a perilous stair that climbs the cliff face to the hall above. Nobody in his right mind went to Ravenscraeg while the Mad Reaver inhabited it, but according to rumor, it has been purchased by a mysterious new owner.

Ravenscraeg lies 2 days’ walk south of Kalsgard in the craggy hills near the Grungir Forest. Once its location is known, the journey to Ravenscraeg can be made in 1 day on horseback or 2 days on foot. The trail passes through boggy terrain south of Kalsgard dotted with small copses and shale hillocks. The gray line of craggy hills is visible to the south and beyond them the green forest.

== Ravenscraeg

The hills rise sharply ahead into a steep and craggy shale escarpment hundreds of feet high. Tucked into a narrow defile between two of these crags is a stone-and-timber longhall and tower, weathered and gray. The hall stands nearly one hundred feet above the base of the cliff, with only a single wooden stair climbing in a series of switchbacks up the cliff face to its front gate. All is silent save for the raucous caws of the ravens that congregate atop the hall’s tower and ridgepole high above.

Invading Ravenscraeg takes four attempts, in between which the heroes rest and recover in Grungir Forest, near the secret trail to the back door of Ravenscraeg, discovered on their first visit. Upon each return, the heroes encounter dwindling but sometimes more strategic reinforcements including Ulfen warriors, ninja, ravens, monks and trolls. On their first assault, the heroes discover a Hellwasp Swarm in a glass case and wisely leave it alone.

They also rescue an Ulfen merchant of Kalsgard named Lute Haggersly. Lute has been imprisoned here for 4 weeks, subsisting on the small portions of food and water given to him by his captors, and whatever rats he has been able to catch. Lute is now a shadow of his former self and is weak with malnutrition and fever, but he has only minor injuries and conditions easily remedied with proper care or minor healing magic. He was abducted from the road on a trip to some of the outlying villages around Kalsgard and was brought here. Lute has primarily faced Goti Runecaster so far, who tried out various noxious brews that he had concocted (fortunately with no overly baneful effects) and threatened him with infestation by the hellwasp swarm. Jorgan the Axe has worked him over a few times as well. Lute can tells the heroes that he has not been questioned and has no idea why he is being held. He warns them that a hideous purple ogre seems to command the fortress, and he claims the ogre is actually none other than Thorborg Silverskorr, the leader of the Rimerunners Guild. Lute is of no help to the party and would prefers to wait at their camp until the heroes escort him back to Kalsgard.

Over the course of their four assaults on Ravenscraeg, the heroes defeat several significant foes, each in turn beginning with the ninja-monk Omoyani, the Frozen Shadows’ training master, followed by the half-troll spriggan sorcerer Goti Runecaster, Thorborg Silverskorr’s most trusted advisor. After recovering in Grungir Forest, the heroes return to defeat the werebear ranger Jorgan the Axe, captain of the guard at Ravenscraeg, followed by the blood-feather raven druid Wodes, spymaster for the Frozen Shadows. On their forth assault the heroes defeat the sniper Hekja, hired assassin and finally Thorborg Silverskorr, in actuality ogre mage Kimandatsu.

The battle with Kimandatsu, pushed the heroes to their limits, but our heroes emerged victorious. After resting and recovering from the battle, they make a thorough search and find both _Suishen_ and Ulf Gormundr. Returning to Kalsgard with Ulf, Lute, _Suishen_ and what treasure they could carry, the heroes return one final time to Ravenscraeg, this time with a full caravan to thoroughly loot the fortress. Returning to Kalsgard with quite the haul, the heroes are greeted by many friendly and grateful citizens. It seems while the heroes were gone, Lute Haggersly publicly revealed the truth about Thorborg Silverskorr and the heroes actions in bringing her to justice, which causes a major shake up in Kalsgard. Sveinn Blood-Eagle suspended the Rimerunners Guild’s operations and seized all of its assets while investigations are conducted, and the Linnorm King immediately and publicly distances himself from his formerly cordial relations with Thorborg Silverskorr.

For their part in avenging his blood feud upon Asvig Longthews and Thorborg Silverskorr, Fynn Snaevald officially relinquishes ownership of _Suishen_ to the heroes as promised. In addition, he offers to invest up to 2,000 gp in Sandru’s caravan in exchange for a cut of any profits. With Ulf Gormundr as a guide, the heroes begin planning for the journey over the Path of Aganhei and through the deadly morozko storms to cross the Crown of the World.

== Suishen, Guardian of the Amatatsu

_Suishen_ reveals much of the history of the Amatatsu family and the oni of the Five Storms, up to the time it was sold to Fynn Snaevald, including identifying both Kikonu (master of Brinewall) and Kimandatsu (master of Ravenscraeg) as members of the Five Storms.

Hundreds of years ago in the distant land of Minkai, a powerful cabal of evil spirits known as oni emerged from the mysterious Forest of Spirits. Intent on seizing control of a land they felt they deserved to rule, these oni, known as the Five Storms, began a covert war against the five royal families of Minkai, for by obscure but nonetheless binding divine laws, only once all five families had been wiped out or controlled could the Five Storms take control. By 4652 AR, the Five Storms had come close to their goal. Yet when the oni turned their attention to this last family of nobles, the Amatatsus, they discovered that the family had fled Minkai over the Crown of the World, the inhospitable northern continent at Golarion’s north pole.

When the exiled Amatatsus emerged from the Crown of the World and staggered into the Linnorm Kingdom city of Kalsgard, their numbers had been reduced to a small fraction of a once-grand dynasty. The youngest and only surviving son, a young man named Amatatsu Tsutoku, took over responsibility for the family and their heritage. Seeing no other options, Tsutoku sold the family’s heirloom sword, the sentient katana _Suishen_, to a local collector in order to raise the funds to continue the journey south and finance a stealthy integration into an alien society. In order to finalize their hidden exile and throw off further pursuit from the Five Storms, the Amatatsus changed their family name to Kaijitsu, and the exiled royals chose new names and switched their order to match Avistan’s naming conventions. Thus did Amatatsu Tsutoku became Rokuro Kaijitsu. Using some of the money they’d received from the sale of _Suishen_, the Kaijitsus secured a home in the small town of Brinewall and paid to have the only remaining proof of their royal lineage, a minor artifact called the _Amatatsu Seal_, held in a magical warding box that blocked divination magic in a secure vault under Brinewall Keep. The Kaijitsus became merchants and glassblowers, hoping that the very idea of a royal family changing its name and working as common merchants would be all but unthinkable to the Five Storms.
