= A Gathering of Shadows

link:../../index.html[Home] » link:../index.html[Jade Regent 2020] » link:index.html[Story Journal]

With few leads other than the knowledge that Suishen may be held at the chieftain’s farm, not to mention the fact that Longthews seems opposed, for unknown reasons, to the heroes’ planned journey over the Crown of the World, a raid on the farm seems prudent.

Asvig’s farm lies a 2-hour walk southeast of the city in an area of lightly forested and marshy hills. Like many of the steadings in the area, Asvig’s farm is a fortified house of sod and stone where the landowner and his retainers can gather for common defense against the dangers of the wild. There are several sheds and outbuildings for mounts, tools, and animals, but none are occupied or of any particular interest. Approaching in daylight, the heroes set an ambush for Asvig's men and light a fire in the fields to draw them out. The heroes suprise and quickly dispatch 20 Ulfen warriors.

== Animal Posts

A ring of short wooden posts driven into the ground surrounds the farm and its outbuildings, spaced every 30 feet at a distance of 60 feet from the farmhouse. The road to the farmhouse passes between two of these posts. These “animal posts” are topped with fancifully carved lion heads (like those on Asvig’s arm-rings) that are obviously the work of a woodcarver who had never actually seen a lion before (as would be the case for most Ulfen artisans). The craftsmanship, however, is of good quality, and gold and red paint highlights the seams and creases in the wood. In addition, runes have been carved running down the length of each post. The heroes recognize the runes on the posts as being related to conjuration magic, and _detect magic_ reveals a moderate aura of conjuration (summoning) on the posts themselves. Before passing between the posts, the heroes notice the smudged remains of runes recently drawn in the dirt and hurriedly erased. They successfully recreate the rune and pass through without incident.

== Asvig’s Farmhouse

The walls of the main house are constructed of courses of sod laid atop stone and average 3 feet thick. Floors are bare dirt covered with fresh grasses or sweet hay and are dug down below ground level to a depth of 3 feet. The roof is thatch above heavy wooden beams and rises to 12 feet at the center (8 feet near the walls), with narrow smoke holes above the fire pits. Doors are of strong wood with no locks, and can be barred from within, though none currently are. In addition to Asvig Longthews and his wife Helva, 17 Ulfen warriors are currently present at the farm, as well as 10 thralls acting as servants.

Despite expecting an attack, the heroes quickly defeat Asvig, Helva and their Ulfen warriors. A search of the farm reveals some treasure, but _Suishen_ cannot be found. The freed thralls however reveal that Asvig’s own ring-giver, an old jarl and renowned viking raider named Snorri Stone-Eye, is scheduled to be burned with his funeral ship at the break of dawn. They likewise confirm that Asvig ordered both the attack on the heroes’ caravan by the _Aril’s Hammer_ and the theft of Fynn Snaevald’s Tian sword (Asvig led that raid himself), though they do not know why. They can confirm that he rented the _Aril’s Hammer_ from the Rimerunners Guild and has frequent dealings with the merchant guild.

== A Finder of Paths

Upon return to Kalsgard, the heroes are met by an inebriated and slightly bruised and battered Varki tracker named *Uksahkka*. Uksahkka claims that her business partner Ulf Gormundr is the best guide this side of the Crown. Uksahkka goes on to explain that Ulf has gone missing, and she fears that some harm might have befallen him. She relates that Ulf’s last job—a great boon that had come to him seemingly out of nowhere, considering he was on the outs with so many merchant guilds—was to develop a new trade route through the Grungir Forest for a local chieftain named Asvig Longthews. Ulf went out to Asvig’s farm nearly a week ago to obtain the final details and initial payment before picking up Uksahkka to join him, but he never came back. A few days ago, Uksahkka herself went out to Asvig’s farm to find out what had happened, but Asvig told her that the no-good Ulf had never shown up for the job. Asvig then ordered his warriors to throw Uksahkka off his land (which explains her bruises and battered condition). With no leads, Uksahkka returned to town and crawled into a bottle to drown her sorrows.

She asks the heroes if they saw any sign of Ulf at the farm and assures the heroes that if they find and rescue Ulf from whatever he has gotten himself into, the crazy fool is sure to be willing to guide them over the Crown of the World out of gratitude, even into the teeth of the morozko.

== The Final Rest of Snorri Stone-Eye

Upon learning there was no sign of Ulf at the farm, Uksahkka asks the heroes to investigate the funeral ship of Snorri Stone-Eye, Asvig's former master, explaining that possessions, servants and enemies are often burned along with the deceased in Ulfen funerals. Uksahkka also informs them that Snorri's pyre-ship is scheduled to be launched an hour after dawn from a peninsula just west of Kalsgard called Spear-shaker’s Point that is often used for the funeral rites of famous warriors, and that the funeral launch will be delayed at least until near nightfall because of a thick pre-dawn fog that will roll in and linger throughout most of the day. When asked how she can be so sure, Uksahkka merely states that Varki shamans have long been known for their affinity with nature. Her father’s sister was a powerful wind whisperer, and some of her aunt’s gift has come down through the bloodline to her.

Uksahkka also reveals that Snorri’s own huscarls—numbering more than three dozen—have taken up positions as honor guards around the funeral ship until the funeral. Infiltrating the vessel and making off with some of its contents will clearly require a bloody and quite possibly futile fight. However, Uksahkka comes through with a solution once again. She explains to the heroes that her people are known for the use of light, paddled boats called kayaks, which ride low in the water, and are maneuverable and— most importantly—quiet. She agrees to meet them at a certain rocky spit not far from Spear-shaker’s Point at an hour before nightfall with enough two-person kayaks to transport all of the heroes. Uksahkka will give them a quick tutorial on the use of the kayaks while they wait for the funeral ship to launch. When the ship drifts by this beach, they can quickly paddle out to the vessel, using the last remnants of the lingering fog to board the ship unnoticed by the mourners on shore, and get Ulf (and the sword) off before the ship starts to burn in earnest. If nothing else, the Varki’s plan allows the heroes all day to rest and recuperate from their ordeal at Asvig’s farm in order to tackle the task at full strength.

Regardless of the veracity of Uksahkka’s claims of blood kinship to weather priests, a thick fog does roll in off the water just before dawn, just as she predicted. Such a fog is a bad omen for a funeral, and it obstructs the view of the mourners, so the funeral is indeed postponed until nightfall.

== Kayak Lessons

Uksahkka meets the heroes at the appointed hour on the rocky spit outside of town. She brings enough two-person kayaks to hold all of them plus one additional passenger (Ulf Gormundr). It is still an hour before sunset, and the honor guard remains in place around Snorri’s funeral ship beyond the spit. The fog has mostly lifted, but enough shreds remain to mask their activities and their boarding of the ship.

Uksahkka spends the next half-hour instructing the heroes on the use of the kayaks, a relatively simple task. After this training, Uksahkka prepares to depart back to town. She fears that Asvig’s associates may be looking for her after the events at the farm and needs to make sure the hiding place she has prepared for Ulf and herself is secure. Uksahkka gives the heroes a clay token with a picture of a songbird stamped on one side. Once they have rescued Ulf, they should present the token to the priest at the shrine of Shelyn in the Fire Quarter, and he will show them to her safe house. Uksahkka then heads off into the dispersing fog.

== The Funeral Ship

Soon after the heroes notice the funeral ship floating by the spit in the thinning fog, a small glow on its deck marking the beginnings of the funeral pyre that will soon consume it. To reach the ship, they must kayak out to the ship before it passes out of sight. The trip is short and smooth, and with Uksahkka’s training, it takes only a few minutes to reach the funeral ship, tie off the kayaks, and board.

The deck of the longship has been built up with planks over the old rowing benches, creating a space belowdecks. It appears that the funerary treasures have been placed in this hold, as the deck is empty save for a silent, shrouded form resting atop a bier in front of the mast, surrounded by stacked wood. A leather sack sits atop small pile of sand at the base of the bier, the glow of flame and wisps of smoke escaping from it.

The pile of sand on the deck is hollowed out and holds an urn of lamp oil within it. A leather bag containing burning coals has been placed over the top of the urn to act as a delayed timer for the fire. As soon as the coals burn through the leather bag, they will land in the oil, igniting the oil and the bier. The heroes place the bag of coals to the side so they can reset the timer to burn the ship before they leave. The hold below the main deck is a cramped space with a low, 4-foot-high ceiling, occupied by rowing benches and stacked funerary treasures worth several thousand gold pieces. Among the funeral treasures of Snorri Stone-Eye is a magnificent winged full helm. It is obviously quite valuable, but out of respect for the dead the heroes leave the treasures alone, seeking only _Suishen_ and Ulf.

Snorri Stone-Eye, the Mad Reaver, lurks in the hold belowdecks. Snorri now exists as a draugr captain, an undead warrior dripping with seaweed and putrid seawater, and has been shackled to the mast by a heavy chain. Although fastened to the mast, the chain is long enough to allow Snorri to move anywhere in the hold. When the heroes first venture into the hold, they can hear chains rattling at the far end of the hold, behind a stack of grave goods. They can trace the chain fastened to the mast to this area, but a thick mist obscures vision in the stern of the ship. When they investigate, they discover that it is not Ulf Gormundr in the stern of the boat, but rather Snorri Stone-Eye himself, who attacks anyone peering over the stacked goods to see him. After defeating Snorri Stone-Eye, a quick search of the ship reveals that neither Ulf Gormundr nor the sword _Suishen_ is present on the ship.

== Smoke on the Water

The heroes suddenly hear the loud "`whump`" of lamp oil catching fire on the deck above, followed by the crackling of the wood in the bier. The funeral ship has caught fire with them still on it! Climbing back up to the deck, the wooden bier has become fully alight and burns brightly at midship. Beyond it in the water you can see the kayaks that brought you here cut loose and drifting out of reach. Tied off at the stern of the ship are two canoes, into which a group of black-clad, masked figures are quickly clambering. Seeing the heroes, the ninja quickly move to attack them. Our heroes quickly defeat the ninja and recover a jade raven statuette dropped by one. Finally the heroes escape in the canoes.

== The Shrine of Shelyn

The heroes enter the Fire Quarter to find Uksahkka at the shrine of Shelyn, using the clay token she gave them. However, their search is interrupted as the sounds of screams and the crashing of tumbling masonry roll down the street over the normal noises of the crowd. Ahead, above the press, the shrine of Shelyn slowly sways and then collapses into the street, dumping its facade of stone and mortared brick on those unfortunates below, resulting in another wave of screams of pain and fear.

A Large earth elemental pounding away at the building and quickly reducing it to rubble. The blood-feather raven perched atop the building across the street commands the elemental to turn its attacks upon the heroes, then flaps out of view behind the building and disappears. The elemental is a challenging foe, taxing the heroes to their limits, but they once again emerge victorious, albeit badly wounded and in need of another round of healing.

The old priest Yin-Po is unconscious but only slightly wounded. When revived, having already been shown the clay chit given to them by Uksahkka, Yin-Po quickly ushers the heroes through the rubble into an alley behind the shrine. He guides them to a secret door to the hidden cellar where Uksahkka is hiding, but the door has been battered down and Uksahkka is nowhere to be found. Apparently the elemental’s attack was a distraction so that unknown agents could gain access to the hiding Varki tracker. All that remains is a large black feather lying in a corner. The feather is much too large to be that of a normal raven or even the large blood-feather raven seen earlier.

== Further Investigations

Asking around pertaining to large raven feathers or black-garbed assassins, reveals that a thieves’ guild known as the Frozen Shadows has come to prominence in Kalsgard in recent years. Its members are rumored to have almost supernatural abilities in stealth and assassination and often leave a large black feather as a calling card. No one knows where the guild is headquartered.

Fortunately for the heroes, they have one additional ally that they are unaware of. The cassisian angel Helgarval (the winged helm seen on Snorri's funeral ship) stumbled upon the doings of the oni of the Five Storms in the Kalsgard area and has spent years quietly observing the oni and their agents and gathering as much information as it could. Helgarval hasn’t been able to learn much more than the heroes, but it has gleaned one vital piece of information: The Rimerunners Guild, a powerful trading guild in Kalsgard, is actually a front for the Frozen Shadows thieves’ guild, who it believes are agents of the Five Storms oni from far-off Minkai. Learning of Snorri StoneEye’s connections with the Rimerunners Guild (and thus with the Frozen Shadows), Helgarval secretly stowed away on the funeral ship, only to find itself trapped belowdecks. The battle at the shrine of Shelyn convinces Helgarval of the heroes' good intentions, so it reveals itself to them at an appropriate time, giving the, the broad strokes of its purpose. In addition, Helgarval has learned that a blood-feather raven (perhaps the same one the heroes have already encountered on multiple occasions) is known to be the familiar of a local spellcaster named Goti Runecaster, and that Goti is a close associate and advisor to Thorborg Silverskorr, head of the Rimerunners Guild.

== The Rimerunners Guild

Specializing in trade with Tian Xia over the Crown of the World as well as along the rivers of the Lands of the Linnorm Kings, the Rimerunners Guild is extremely influential in and around Kalsgard, with many local merchants and their retainers and much of the local economy beholden to it. A merchant of high repute named Thorborg Silverskorr leads the guild, but she is rarely seen in public, and has numerous connections with the wealthy and powerful of Kalsgard, including Linnorm King Sveinn Blood-Eagle himself. The Rimerunners’ guildhall is located on the waterfront in the Jade Quarter, and is staffed by dozens of well-armed guards, both day and night.

== Investigating the Rimerunners

The Rimerunners are powerful and influential (as well as a possible front for a guild of thieves and assassins), and are likely far too powerful for the PCs to confront directly. In addition to the normal guards posted throughout the guildhall, dozens of armed guards, members of the city watch, and witnesses may be found near the guildhall at any time during the day, making any sort of direct frontal assault unwise at best. At the same time, Thorborg Silverskorr and Goti Runecaster are seldom seen in public, so locating them individually is likely out of the question.

== The Rimerunners Guildhall

The Rimerunners guildhall has exterior masonry walls 2 feet thick, with a roof of sturdy shake shingles. The chimneys are lead pipes only 8 inches in diameter, and stout wooden shutters and iron bars block all of the windows. All doors and window shutters are of strong wooden construction, and the doors are locked and shutters barred at night. The heroes break into the
guildhall before dawn by stealth, blocking the chimney and the bright red sparks meant as an alarm to attact the city guard partrols. This delays potential reinforcements, giving the heroes time to overcome the six guards and search the guildhall.

In a hidden room, the heroes find and open a strongbox, inside they find many mundane business documents and financial records of the guild. With time to go through the documents, the heroes easily confirm that the _Aril’s Hammer_ was rented to Asvig Longthews on the night of the attack at Skalsbridge, and that he was contracted by the guild to "`acquire a Tian antique`" from a specific address recognizable as that of Fynn Snaevald’s house (a reference to Asvig’s theft of _Suishen_). More importantly, they locate ledgers detailing financial transactions transferring large sums of money over the last few years (as well as the aforementioned "`Tian antique`") to a location called Ravenscraeg. These "`development expenses`" were all personally approved by Thorborg Silverskorr—not a smoking gun in and of itself, but certainly evidence that this Ravenscraeg and its secrecy is of importance to Silverskorr. The documents also reveal that the Rimerunners purchased Ravenscraeg from Snorri Stone-Eye 3 years ago.

The heroes also find Uksahkka in a guest chamber converted into a makeshift prison, the Varki tracker has been roughed up some, but is otherwise none the worse for wear. She tells the heroes that she overheard her captors speaking about transferring her to a place called Ravenscraeg, where Ulf Gormundr is also apparently being held. She will not accompany them there, however, as her recent experiences have soured her on life in Kalsgard. She is ready to wash her hands of the entire business, and plans to leave the city as soon as possible.
