= To the World’s End

link:../../index.html[Home] » link:../index.html[Jade Regent 2020] » link:index.html[Story Journal]

The heroes and their caravan head north into the Crown of the World, under the guidance of Ulf Gormundr. The initial passage beyond the northern mountains of Avistan is surprisingly easy, but the caravan must make choices about how best to proceed—should they take the easier road following the Path of Aganhei, likely much faster but perhaps more exposed to unfriendly eyes, or a more difficult shortcut through the rugged wilderness? Ulf Gormundr, promises to lead them through landscapes more desolate than any they have ever known, yet at the end lies the promise of justice for the Kaijitsu family, and fortune and glory in a realm unlike any in Avistan.

== Time and Travel

The heroes’ journey across the Crown of the World is not a race against time; in fact, it is the opposite. The goal is to safely escort Ameiko to Tian Xia over the Crown of the World, a journey of over 3,000 miles across unforgiving terrain and through both bitter weather and extremes of light and darkness, while dealing with the icy continent’s dangerous inhabitants. In the best of conditions, at a standard speed of 32 miles per day, an average caravan takes a minimum of 94 days, or just over 3 months, to make the journey, and often takes half a year or more—a significant factor in most caravan masters’ decisions to make the crossing only once a year in the height of summer. The journey could even take over a year if they take breaks to craft magic items, explore, or simply rest during the journey—and that is just fine!
