= To the World’s End

link:../../index.html[Home] » link:../index.html[Jade Regent 2020] » link:index.html[Story Journal]

The heroes and their caravan head north into the Crown of the World, under the guidance of Ulf Gormundr. The initial passage beyond the northern mountains of Avistan is surprisingly easy, but the caravan must make choices about how best to proceed—should they take the easier road following the Path of Aganhei, likely much faster but perhaps more exposed to unfriendly eyes, or a more difficult shortcut through the rugged wilderness? Ulf Gormundr, promises to lead them through landscapes more desolate than any they have ever known, yet at the end lies the promise of justice for the Kaijitsu family, and fortune and glory in a realm unlike any in Avistan.

The heroes and their caravan, under Ulf’s guidance, cross the Arctic Circle and enter the Crown of the World. To reach this point, the heroes left Kalsgard after the winter solstice festival and feigned heading north threw the western Path of Aganhei, but instead turned east and traveled through the Thanelands of the Linnorm Kingdoms, Irrisen the Land of Eternal Winter and the Realm of the Mammoth Lords. The trip was relatively uneventful and the caravan traded along the way, before turning north at Icestair to cross the Stormspear Mountains. It was hoped this would throw off any pursuers and at least confuse their enemies, adding more than a month to the journey to Minkai. Following the Path of Aganhei's eastern route from Icestair to cross the Rimethirst Mountains, the caravan stays off “the path” to disguise its movements and stay hidden, when and where possible.

== Time and Travel

The heroes’ journey across the Crown of the World is not a race against time; in fact, it is the opposite. The goal is to safely escort Ameiko to Tian Xia over the Crown of the World, a journey of over 3,000 miles across unforgiving terrain and through both bitter weather and extremes of light and darkness, while dealing with the icy continent’s dangerous inhabitants. In the best of conditions, at a standard speed of 32 miles per day, an average caravan takes a minimum of 94 days, or just over 3 months, to make the journey, and often takes half a year or more—a significant factor in most caravan masters’ decisions to make the crossing only once a year in the height of summer. The journey could even take over a year if they take breaks to craft magic items, explore, or simply rest during the journey—and that is just fine!

== The Hill Country

Bitter cold, driving wind and snow, deep drifts of snow, treacherous spirits and hidden crevasses variously slow and delay the caravan. Often choosing the less taken paths to avoid notice, the heroes turn off the primary Path of Aganhei to travel through the Gaarjuk Hills and avoid the lake country. Stopping at the small Erutaki village of Rimakak to rest and resupply the caravan, they find Rimakak’s lodges and huts deserted. Lured onto the ice of Lake Nallishoot, the heroes are attacked by a qallupilluk, a sinister and much dreaded hag-like denizen of the far northern seas, feared as child snatchers who steal the young and drag them below the waves, to be enslaved and transformed into horrible scaled monstrosities. After liberating Rimakak of the monster and her merrow “children”, the heroes continue their journey north where the caravan is trapped in an avalanche and attacked by an Arctic Chimera. After defeating the chimera and freeing the caravan from the fallen debris, ice and snow, the heroes once again continue their trek north whereupon they encounter an Erutaki clan living in buried sod huts along the Kluani River. They are greeted with an offer of fire and food, but upon identifing the proffered meat as being human and displaying revulsion about the tribe’s lifestyle, the cannibals immediately became hostile insisting the heroes leave immediately. Complying the heroes continued their journey once more.
